MySQL with Node.js
section-io/engineering-education pull request #1016
Opened 2020-12-18 22:34 UTC by kimkimani

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-12-22 16:12 UTC, hectorkambow commented
plagiarism check done

2020-12-26 06:25 UTC, zolomohan reviewed
@kimkimani 
Overall, a great article. 

Add Alt Text for every image in the article, something relevant to the image.

2020-12-26 06:25 UTC, zolomohan commented on articles/mysql-with-node-js/index.md
> +Follow [the following steps](https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server).
You can say, Follow these steps instead of Follow the following steps.

2020-12-26 06:25 UTC, zolomohan commented on articles/mysql-with-node-js/index.md
> +We need to create a database that we will store our information. Create a function `createDB()`. We will use this function to create a new database. After making a successful connection, call the fun
Remove `we` in `We need to create a database that we will store our information`.

2020-12-26 06:25 UTC, zolomohan commented on articles/mysql-with-node-js/index.md
> +[Getting to Grips with MongoDB Database](/engineering-education/working-with-databases-part1/)
Mark these as bullet points.

2020-12-27 11:51 UTC, zolomohan approved these changes

2020-12-27 12:06 UTC, zolomohan requested changes
@kimkimani 
Add Alt text for all the images in the article and we can move to the final review.

The article passed the tech review.

2020-12-27 16:51 UTC, kimkimani commented
@zolomohan Thank you for the good work Ive added Alt text for all the images

2020-12-27 21:23 UTC, zolomohan approved these changes

2021-01-08 12:50 UTC, louisefindlay23 commented
@hectorkambow, final review check has been completed.

2021-01-10 20:45 UTC, merged