Creating a Django Hello World App Using PostgreSQL Database
section-io/engineering-education pull request #1026
Opened 2020-12-19 22:37 UTC by atoyegbe

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-12-28 16:49 UTC, hectorkambow commented
@atoyegbe 
👋  Good morning and thank you v much for submitting your 1st article to the EngEd Program. 

We're happy to have you join us. 

Quick FYI - upon running your article through our 3rd party plagiarism checker it raised a few red flags and the % was a bit higher than typically accept. 

Please review the PDF and be sure to add sources and citations to the article as articles where needed. 

Here is a link to help with any [confusion regarding plagiarism](https://www.scribbr.com/category/plagiarism/)

Below is the PDF.
[Creating a Django Hello World App Using PostgreSQL Database #1026.pdf](https://github.com/section-io/engineering-education/files/5748116/Creating.a.Django.Hello.World.App.Using.PostgreSQL.Database.1026.pdf)
).

Thank you 👍

2020-12-28 19:25 UTC, atoyegbe commented
Added References @hectorkambow

2020-12-29 08:54 UTC, zolomohan requested changes
Hi @atoyegbe.
I noticed a lot of grammatical errors in your article. Please run your article through Grammarly and Hemmingway to improve this article.

Also, a lot of your lines are starting like, creating... installing...
Instead, you can start these lines like, Let's create..., Let's install.

Make sure you are punctuating the sentences properly. I noticed the first word of a lot of sentences aren't capitalized. Make sure you are capitalizing them properly.

2020-12-29 08:54 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +### Step 1 - Create a database and database user we will be creating our database through the command line.
Keep the headings short. 

`we will be creating our database through the command line.`

This line can be added inside the section.

2020-12-29 08:54 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +creating a virtual environment and activate it.
You can rewrite it as, Let's create a new virtual environment and activate it.

2020-12-29 08:54 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +creating a app in our django_app project
Explain what an app is in Django.

2020-12-29 08:54 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +To make sure our django templates is now working let go me work you through this short steps
Rewrite this line. `let go me work you through this short steps`. This part doesn't make sense.

2020-12-29 09:44 UTC, atoyegbe commented
made changes @zolomohan

2020-12-29 09:54 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +### Step 1 - Create a database and database user we will be creating our database through the command line.
This is not done yet.

2020-12-29 10:16 UTC, zolomohan requested changes
@atoyegbe 
Since this is a Hello World application tutorial, You need to explain all the basic terminologies. I noticed you didn't explain most of the terminologies and what each file does. For example, what's the functionality of a `views.py` file or `urls.py` file. Please explain all the terminologies and provide links for documentations that has further explanations.

2020-12-29 10:16 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +Let's create a virtual environment and activate it.
Explain why you need a Virtual ENV and why you need to activate it.

2020-12-29 10:16 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +  - psycopg2 is a popular PostgreSQL database adapter for python programming language.
Why is this marked as a bullet point? Please make it a normal line.

2020-12-29 10:16 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +> A Django application is a Python package that is specifically intended for use in a Django project. Django apps are reusable in different Django project. [Django](https://www.djangoproject.com)
Remove the Django link at the end. Provide a link for an article or documentation that explains Django apps in further detail.

2020-12-29 10:16 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +We need to plug our hello_world app to our django_app to do this navigate to
`We need to plug our hello_world app to our django_app`.

to -> into
Break the line after django_app. `To do this, navigate to` should be a separate line

2020-12-29 10:16 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +```
Instruct readers to add the app name in Installed apps. It will be unclear if you just provide a snippet.

2020-12-29 10:16 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +go to the DATABASE SECTION
Proper punctuation required.

2020-12-29 10:16 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +```
Explain what `makemigrations` and `migrate` command does.

2020-12-29 10:16 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +First, let create a templates folder in our django_app/templates directory and create an index.html file. Your project directory should look like this.
Explain about templates.

2020-12-29 10:16 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +    ```
Can you briefly explain what `urls.py` and `views.py` does?

2020-12-29 10:16 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +# Hello World
You didn't instruct the readers to add anything in `index.html`

2020-12-29 14:30 UTC, atoyegbe commented
made changes @zolomohan

2020-12-30 10:30 UTC, zolomohan requested changes
@atoyegbe I've left some more suggestions. Please go through them all.

2020-12-30 10:30 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +```
Briefly explain what these commands are.

2020-12-30 10:30 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +```
Briefly explain what these commands are and why this is necessary.

2020-12-30 10:30 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +```
It would be great if you split this into two code snippets and explain them seperately.

2020-12-30 10:30 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +```
Split the code snippets and explain the role of each command.

2020-12-30 10:30 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +Let's install `django` and `psycopg2` packages using `pip`. `psycopg2` is a popular PostgreSQL database adapter for python programming language.
Explain briefly about `pip` and provide a link to the pip homepage.

2020-12-30 10:30 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +```
Explanation required for why you are doing this.

2020-12-30 10:30 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +```
Explain that the default database is set to SQLlite and we are going to change it to PostgreSQL

2020-12-30 10:30 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +```
Explain briefly about manage.py file

2020-12-30 10:30 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +The templates directory is the display layer which handles User Interface of our Django project.
Better explanation required.

2020-12-30 10:30 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +The above code in our **urls.py** file maps `homepage()` in the **views.py** to **127.0.0.1:8000/**.
It will not map to `127.0.0.1:8000/`. It will just map it to `/`.

2020-12-30 10:30 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +Visit **127.0.0.1:8000** in your browser. You will see Hello World.
Add a screenshot of the webpage.

2020-12-30 21:01 UTC, atoyegbe commented
made changes @zolomohan

2020-12-31 09:16 UTC, zolomohan commented
Hi @atoyegbe. The article passed the tech review. The code snippets are working as expected.

But, It seems like you removed the make migrations and migrate section from the article. It is definitely an important topic to cover when we are talking about databases in Django. Please add it back to the article and explain it briefly.

2020-12-31 09:18 UTC, zolomohan commented
When you made changes last time, you accidentally reverted all my changes. Please make sure that doesn't happen again. 

Pull this branch using `git pull origin <branch-name>` to get the changes I made and then proceed to make your changes.

2020-12-31 09:23 UTC, zolomohan commented
Please add a Hero image which is about 600x400 in dimension. Name the image as `hero.jpg` .

2020-12-31 09:55 UTC, atoyegbe commented
Hi @zolomohan 
I removed the makemigrations and migrate command cause i don't have any models in the models.py file. If I'm to explain what makemigrations and migrate command will have to define a model. What do you suggest?

2020-12-31 10:16 UTC, zolomohan commented
> Hi @zolomohan
> I removed the makemigrations and migrate command cause i don't have any models in the models.py file. If I'm to explain what makemigrations and migrate command does, I will have to define a model. What do you suggest?

hmm, I think there will be some default tables that'll get migrated.

2020-12-31 11:33 UTC, atoyegbe commented
made changes @zolomohan

2020-12-31 12:49 UTC, zolomohan commented on articles/django-app-using-postgresql-database/index.md
> +When you run it for the first time, the default models in the Django project will get migrated.
Please mention that the `makemigrations` command created a file with all the SQL commands that will be run while running the `migrate` command. This is the most important part of the `makemigrations` command.

2020-12-31 12:50 UTC, zolomohan commented
Also, please run your article through Grammarly once more.

2021-01-01 02:50 UTC, zolomohan commented
@atoyegbe
Since you are a first-time contributor, can you add a folder with your name in the `author` directory and say something about yourselves along with an image.

Folder structure:

```
--authors
| ---your-name
|     --- avatar.jpeg
|     --- index.md
```

2021-01-01 07:59 UTC, atoyegbe commented
Done

2021-01-01 08:40 UTC, zolomohan approved these changes

2021-01-12 17:30 UTC, merged