Mathematics for machine learning
section-io/engineering-education pull request #1029
Opened 2020-12-20 14:15 UTC by Bayler

Fixed #651

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-12-23 06:38 UTC, lalith1403 requested changes
Add links to all the topics mentioned. Find resources and insert links. Let us make sure anyone starting with ML can use this as reference material to access top-notch material.

2020-12-23 06:38 UTC, lalith1403 commented on articles/mathematics-for-machine-learning/index.md
> +### Probability $ Statistics
Probability and Statistics

2020-12-23 06:38 UTC, lalith1403 commented on articles/mathematics-for-machine-learning/index.md
> +Linear Algebra covers a significant part of the mathematical concepts used for Machine Learning. According to [Wikipedia](https://en.wikipedia.org/wiki/Linear_algebra/), Linear Algebra is a mathemati
Just mention Linear algebra is a subdomain dealing with linear systems of equations. Remove the line according to wikipedia.

2020-12-23 06:38 UTC, lalith1403 commented on articles/mathematics-for-machine-learning/index.md
> +The topics in Linear Algebra essential for understanding the methods used in machine learning include:
Add links to resources to each of these topics. See this as a list of resources. So adding links to each of these resources will enhance the value delivered. Give a link for each subtopic under each subject.

2020-12-28 16:51 UTC, hectorkambow commented
Plagiarism check done

2021-01-12 19:16 UTC, merged