Reproducibility to Improve Machine Learning
section-io/engineering-education pull request #1030
Opened 2020-12-20 19:58 UTC by collins-a

Article as index.md.
hero image as hero.jpg

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-12-20 19:59 UTC, collins-a commented
This fixes #894

2020-12-23 06:43 UTC, lalith1403 requested changes
Amazing article. Elaborate on reproducibility under non-deterministic algorithms.

2020-12-23 06:43 UTC, lalith1403 commented on articles/reproducibility/index.md
> +The potential solution to this is a simple one; keenness to order. Engineers should be keen on the order in which they pass features, hyperparameters as well as when to introduce [seed values](https:
Explain seeding as a way to ensure reproducibility. If required, insert a code snippet of numpy using this concept. np,random(seed=#).

2020-12-23 06:43 UTC, lalith1403 commented on articles/reproducibility/index.md
> +Deterministic algorithms produce the same output given the same input, even on different iterations. However, there exist many algorithms that display non-determinism. Reproducibility in such algorit
How do we deal with non-deterministic algorithms? How do we ensure reproducibility in this case?

2020-12-24 12:14 UTC, collins-a commented
Hey @lalith1403, thank you for the quality review. I have made the requested changes. Cheers!

2020-12-28 16:59 UTC, hectorkambow commented
plagiarism check done

2020-12-30 14:33 UTC, lalith1403 approved these changes

2021-01-13 00:04 UTC, merged