Minimizing Data Leakage in Machine Learning
section-io/engineering-education pull request #1038
Opened 2020-12-21 18:06 UTC by collins-a

Article as index.md.
Hero image as hero.jpg.

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-12-21 18:07 UTC, collins-a commented
This fixes #803

2020-12-23 06:15 UTC, lalith1403 requested changes
Amazing article. Elaborate on a few points and this should be good to go.

2020-12-23 06:15 UTC, lalith1403 commented on articles/data-leakage/index.md
> +It is standard to split data into separate groups such as testing, training, and validation sets. Not all models require a validation set since we can train a model using the training set and use the
Interesting point. But, how would the two sets get mixed up? Elaborate on that.

2020-12-23 06:15 UTC, lalith1403 commented on articles/data-leakage/index.md
> +### Closing
Conclusion or Wrapping up is more apt.

2020-12-23 06:15 UTC, lalith1403 commented on articles/data-leakage/index.md
> +For instance, data leakage will occur in a scenario where one carries out normalization of an entire dataset, then evaluates the algorithm's performance using cross-validation. [Normalization](https:
There are different types of normalization. The last sentence is true only in a specific kind. There are min-max normalization, mean-subtraction, etc. Remove the last sentence.

2020-12-23 06:15 UTC, lalith1403 commented on articles/data-leakage/index.md
> +From the example above, a clear mistake is the normalizing of an entire dataset. We should note that normalization needs to be carried out after splitting data into train, test, and validation sets.
It is clear that normalization affects the results. But, how does the order of events change the results? Can you elaborate on that?

2020-12-27 11:10 UTC, collins-a commented
Hello @lalith1403, thanks as always, made the requested changes. Check them out when you can. Cheers and happy holidays!

2020-12-28 17:29 UTC, hectorkambow commented
plagiarism check done.

2020-12-30 14:35 UTC, lalith1403 approved these changes

2021-01-13 20:10 UTC, merged