introduction-to-processors
section-io/engineering-education pull request #1039
Opened 2020-12-21 18:45 UTC by WangechiMurimi

Fixes #919 
### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-12-23 06:04 UTC, lalith1403 requested changes
Amazing article. It is a good guide for beginners. Explain pipelining in detail, and focus on adding an introduction to the x86 instruction set.

2020-12-23 06:04 UTC, lalith1403 commented on articles/introduction-to-processors/index.md
> +To understand how code is turned from human-readable to machine-readable then executed, we shall use the __x86 Instruction Set Architecture__. This refers to a series of microprocessors developed by
Can you elaborate on the x86 instruction set?Additional information is required.

2020-12-23 06:04 UTC, lalith1403 commented on articles/introduction-to-processors/index.md
> +The 8086 utilizes _pipelining_ to improve performance. This is a technique that balances the fetching and execution of an instruction, i.e., while an instruction is being executed, another is fetched
Explain pipelining using a timing diagram.

2020-12-23 06:04 UTC, lalith1403 commented on articles/introduction-to-processors/index.md
> +In this article, we have outlined the basic functionality of a processor. In the next article, we will dive into the details using the x86 Processor’s Instruction Set Architecture.
Some more details in this article would add more value to the readers. Give an introduction here to the instruction set. In the next article, go in depth.

2020-12-23 06:04 UTC, lalith1403 commented on articles/introduction-to-processors/index.md
> +The 8086 microprocessor is divided into two functional parts: __Bus Interface Unit__(BIU) and the __Execution Unit__(EU). The Bus Interface Unit provides the interface of 8086 to external memory and
Add an image here!

2020-12-23 06:04 UTC, lalith1403 commented on articles/introduction-to-processors/index.md
> +The 8086 microprocessor is divided into two functional parts: __Bus Interface Unit__(BIU) and the __Execution Unit__(EU). The Bus Interface Unit provides the interface of 8086 to external memory and
for both BIU and EU.

2020-12-28 17:42 UTC, hectorkambow commented
@WangechiMurimi  
👋 Good morning and thank you v much for submitting your 1st article to the EngEd Program.  

We're happy to have you join us.

Quick FYI - upon running your article through our 3rd party plagiarism checker it raised a few red flags and the % was higher than typically accept.

Please review the PDF and be sure to add sources and citations to the article as articles where needed.

Here is a link to help with any [confusion regarding plagiarism](https://www.scribbr.com/category/plagiarism/) - as we strive to create both informative and unique content for the community.

Note: The code should also be as original as possible - unless you are referencing specific frameworks or boilerplate needed to run the program (code snippet). 👍 

Below is the PDF.
[introduction-to-processors #1039.pdf](https://github.com/section-io/engineering-education/files/5748277/introduction-to-processors.1039.pdf)

Thank you 👍

2021-01-20 08:30 UTC, lalith1403 commented
@WangechiMurimi Do you plan to make changes to the article anytime soon? Let us know your timeline so that we can allocate resources accordingly.

2021-01-22 23:41 UTC, hectorkambow commented
Just closing the article for now to clear up the queue @WangechiMurimi  
Can be re-opened at anytime to continue.

2021-01-22 23:41 UTC, closed without merging