An Overview of Meta-Learning
section-io/engineering-education pull request #1048
Opened 2020-12-22 17:18 UTC by collins-a

Article as index.md.
Hero image as hero.jpg.
Maml.png also included.

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-12-22 17:20 UTC, collins-a commented
This fixes #888

2020-12-23 05:49 UTC, lalith1403 requested changes
Amazing article @collins-a. Few minor changes required.

2020-12-23 05:49 UTC, lalith1403 commented on articles/meta-learning/index.md
> +Wikipedia defines a [hyperparameter](https://en.wikipedia.org/wiki/Hyperparameter_(machine_learning)) as a parameter whose value is used to control the learning process. It is a parameter that is def
Need not say Wikipedia defines hyperparameter. The definition of hyperparameter is a standard one.

2020-12-23 05:49 UTC, lalith1403 commented on articles/meta-learning/index.md
> +[Gradient descent](https://ml-cheatsheet.readthedocs.io/en/latest/gradient_descent.html#:~:text=Gradient%20Descent.%20Gradient%20descent%20is%20an%20optimization%20algorithm,descent%20to%20update%20t
I don't think GD is a nature-based optimization algorithm. Ant-colonisation, PSO, etc are nature inspired.

2020-12-24 12:23 UTC, collins-a commented
@lalith1403 thank you, made a couple of tweaks. Cheers!

2020-12-28 17:31 UTC, hectorkambow commented
Plagiarism check done

2021-01-13 22:37 UTC, merged