submitted article and hero image
section-io/engineering-education pull request #1106
Opened 2020-12-30 10:17 UTC by EKahuha

this fixes #1004

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-12-31 09:54 UTC, lalith1403 requested changes

2020-12-31 09:54 UTC, lalith1403 commented on articles/5-real-life-use-cases-of-5g-ultra-reliable-low-latency-communication-urllc/index.md
> +5G URLLC service makes it possible to support use cases that require very high reliability and extremely low latency. Examples of these use cases include industrial automation, intelligent transporta
Expand the abbreviation, even though you have done it in the title!

2020-12-31 09:54 UTC, lalith1403 commented on articles/5-real-life-use-cases-of-5g-ultra-reliable-low-latency-communication-urllc/index.md
> +### Conclusion
You can talk about the challenges as well in implementing these applications. The reason is, 5G is promising a future that you have clearly captured. However, the reader should also know about the challenges of implementing and succeeding in these applications.

2021-01-02 09:20 UTC, EKahuha commented
@lalith1403 
 I have updated this article.

2021-01-06 11:20 UTC, lalith1403 approved these changes

2021-01-14 17:44 UTC, hectorkambow commented
plagiarism check done

2021-01-17 19:22 UTC, merged