How to create Django Docker images
section-io/engineering-education pull request #1110
Opened 2020-12-30 18:02 UTC by paulodhiambo

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-01-05 16:14 UTC, hectorkambow commented
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

2021-01-20 02:16 UTC, geoffrey45 commented
@hectorkambow this article needs a plagiarism check.

2021-01-20 02:19 UTC, hectorkambow commented
plagiarism check done

2021-01-21 11:42 UTC, geoffrey45 requested changes
@paulodhiambo Great article. I was looking at your article and came across a few minor issues. Please make the changes and ping me when you are done.

2021-01-21 11:42 UTC, geoffrey45 commented on articles/django-docker/index.md
> +
Docker images are used to create Docker containers. Please update your explanation.

2021-01-21 11:42 UTC, geoffrey45 commented on articles/django-docker/index.md
> +```
Replace the comma (,) in the word "requirements,txt" with a dot (.)

2021-01-21 11:42 UTC, geoffrey45 commented on articles/django-docker/index.md
> +- **FROM** directive sets the base image from which the Docker container will be built.
Add the article 'a' before the word 'Dockerfile' in line 75

2021-01-21 11:42 UTC, geoffrey45 commented on articles/django-docker/index.md
> +```
Please indicate that everything under `< >` needs to be replaced with real values.

2021-01-21 11:50 UTC, geoffrey45 commented on articles/django-docker/index.md
> +
Add 'the' before the word 'Docker' in this heading.

2021-01-21 12:49 UTC, paulodhiambo commented
@geoffrey45 I have made all the recommended changes.

2021-01-22 11:15 UTC, geoffrey45 approved these changes

2021-01-22 11:15 UTC, geoffrey45 commented
@hectorkambow technical review done. Ready for final review.

2021-01-22 19:15 UTC, merged