Introduction to dynamic programming
section-io/engineering-education pull request #1113
Opened 2020-12-30 19:12 UTC by adithbharadwaj

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1088

2020-12-30 19:15 UTC, adithbharadwaj commented
@hectorkambow , Since this tutorial is the successor of my previous article(recursion) which is under review, I have added the link to what I believe will be the URL for the article on recursion. If these articles are published together, it would be great if someone can add the correct link to the previous article on recursion: #1089

2021-01-06 11:29 UTC, lalith1403 requested changes

2021-01-06 11:29 UTC, lalith1403 commented on articles/introduction-to-dynamic-programming/index.md
> +A better way to solve this would be to store all the intermediate results to calculate them once. There are two ways to do this, but in this article, we will explore one method called tabulation. To
What is the other method? Briefly describe the method. Also, break the para into 2 smaller paras.

2021-01-06 11:29 UTC, lalith1403 commented on articles/introduction-to-dynamic-programming/index.md
> +According to [educative](https://www.educative.io/courses/grokking-dynamic-programming-patterns-for-coding-interviews/m2G1pAq0OO0), Dynamic Programming (DP) is an algorithmic technique for solving an
Did educative define DP? It would be better if the definition is stated and the link is inserted without saying according to educative.

2021-01-06 11:30 UTC, lalith1403 commented
> @hectorkambow , Since this tutorial is the successor of my previous article(recursion) which is under review, I have added the link to what I believe will be the URL for the article on recursion. If these articles are published together, it would be great if someone can add the correct link to the previous article on recursion: #1089

Let us know once the article is published, Insert the link to the article in the comment box. Will add it during the final round of review.

2021-01-06 15:41 UTC, adithbharadwaj commented
> > @hectorkambow , Since this tutorial is the successor of my previous article(recursion) which is under review, I have added the link to what I believe will be the URL for the article on recursion. If these articles are published together, it would be great if someone can add the correct link to the previous article on recursion: #1089
> 
> Let us know once the article is published, Insert the link to the article in the comment box. Will add it during the final round of review.

Thanks for the changes @lalith1403 . I will do that once the article is published

2021-01-14 18:21 UTC, hectorkambow commented
plagiarism check done

2021-01-15 04:58 UTC, lalith1403 approved these changes

2021-01-17 17:48 UTC, merged