Creating an animation counter in JavaScript
section-io/engineering-education pull request #1124
Opened 2020-12-31 11:12 UTC by Agusioma

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1107

2021-01-04 11:37 UTC, kayere commented
@Agusioma - Please avoid making changes to the PR (unless asked to). This might disrupt the review process.

2021-01-04 11:38 UTC, Agusioma commented
Noted. @kayere

2021-01-08 15:27 UTC, kayere requested changes
Hello @Agusioma, I have just gone through your article. Everything works perfectly fine. However, I'd suggest you restructure the article. I can see you only have one subheading; which is not appealing. To add to that, the article's word count (excluding code snippets) is less than 750. Consider adding more content (like conclusion)to satisfy the minimum word count requirement. Revise the article and notify me when you have made the changes.

2021-01-08 15:27 UTC, kayere commented on articles/animation-counter-javascript/index.md
> +function animate(obj, initVal, lastVal, duration) {
Remove this redundant code snippet.

2021-01-08 15:35 UTC, Agusioma commented
Noted. Thank you

2021-01-08 21:13 UTC, Agusioma commented on articles/animation-counter-javascript/index.md
> +function animate(obj, initVal, lastVal, duration) {
Done

2021-01-08 21:17 UTC, Agusioma commented
@kayere I have done the requested changes. Please check

2021-01-12 13:43 UTC, kayere approved these changes

2021-01-14 19:11 UTC, hectorkambow commented
plagiarism check done

2021-01-15 20:58 UTC, louisefindlay23 approved these changes
@hectorkambow, this is ready for publication.

2021-01-15 21:08 UTC, kayere commented
Hello @louisefindlay23, I think you have made changes to the wrong PR👀🤔

2021-01-15 21:13 UTC, hectorkambow commented
@Agusioma 
Noticing that there is multiple index files on this PR - not sure if it was something we did on our side or if the PR was created like this

2021-01-15 21:14 UTC, hectorkambow commented
> Hello @louisefindlay23, I think you have made changes to the wrong PR👀🤔

@kayere  

Louise has been helping go through PR for final reviews. That may be why she was making some edits. 

One thing I noticed though is this PR has multiple index file (more than one article).

2021-01-15 21:18 UTC, Agusioma commented
@hectorkambow it's on your side because right now am not seeing my article here

2021-01-15 21:23 UTC, louisefindlay23 commented
That's it corrected, @hectorkambow and @kayere.

2021-01-15 21:23 UTC, kayere commented
> > Hello @louisefindlay23, I think you have made changes to the wrong PReyesthinking
> 
> @kayere
> 
> Louise has been helping go through PR for final reviews. That may be why she was making some edits.
> 
> One thing I noticed though is this PR has multiple index file (more than one article).

Oow ...I see.😎

The article was fine at the time of my review. I think the commits that followed resulted to that.

2021-01-15 21:24 UTC, kayere commented
> That's it corrected, @hectorkambow and @kayere.

Awesome

2021-01-15 21:34 UTC, Agusioma commented
@louisefindlay23 it's like you deleted the wrong article. It was the one belonging to this PR.

2021-01-16 17:03 UTC, merged