Maria database
section-io/engineering-education pull request #1125
Opened 2020-12-31 12:15 UTC by Erastuskanyatta

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
This fixes #1018

2021-01-05 16:07 UTC, hectorkambow commented
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

2021-01-07 11:50 UTC, Erastuskanyatta commented
@hectorkambow. Any Progress?

2021-01-20 19:52 UTC, hectorkambow commented
plagiarism check done

2021-01-22 08:20 UTC, WanjaMIKE commented
@Erastuskanyatta 
In progress.

2021-01-22 08:23 UTC, Erastuskanyatta commented
@WanjaMIKE  
Thankyou

2021-01-22 08:24 UTC, WanjaMIKE commented on articles/mariadb/index.md
>  Working with the Database seems to be very complicated in a Developer's coding life. But to me, this is not the case. In this article, we will prove how easy it is to work with MariaDatabase with onl
In the Introduction, could you please discuss more what MariaDB entails

2021-01-22 08:25 UTC, WanjaMIKE commented on articles/mariadb/index.md
> +## Step 1: Installing Xampp
The preferred heading is `###` rather than `##`

2021-01-22 08:30 UTC, WanjaMIKE commented on articles/mariadb/index.md
>  Xampp comes along with PhpMyAdmin when downloaded into a machine.  PhpMyAdmin is the MariaDatabase that we will be working on within this article.
Regarding this sentence
`PhpMyAdmin is the MariaDatabase that we will be working on within this article.`
PhpMyAdmin is merely the tool to help manage the database. Make correction

2021-01-22 08:32 UTC, WanjaMIKE commented on articles/mariadb/index.md
> +## . Download the package to be installed.
No need for this section instead go straight to the contents. Remove the heading.

2021-01-22 08:35 UTC, WanjaMIKE commented on articles/mariadb/index.md
Begin all the sentences in the list with a capital letter.

2021-01-22 08:45 UTC, WanjaMIKE requested changes
Nice article @Erastuskanyatta. Quite Informative and easy to understand. Cold you please the following minor changes. Also, inform the readers in the intro that your are using linux. Thanks

2021-01-22 22:30 UTC, Erastuskanyatta commented
@WanjaMIKE  minor changes completed. Please proceed.

2021-01-23 08:01 UTC, WanjaMIKE approved these changes

2021-01-23 14:57 UTC, merged