NPM vs NPX
section-io/engineering-education pull request #1131
Opened 2020-12-31 17:09 UTC by kimkimani

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
FIXES #1011

2021-01-05 16:13 UTC, hectorkambow commented
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

2021-01-16 02:19 UTC, hectorkambow commented
plagiarism check done

2021-01-16 09:40 UTC, zolomohan requested changes
@kimkimani Please go through the suggestions I've left below. I noticed some points were repetitive, especially the fact that NPX caches the packages and doesn't install them. Please remove redundant points.

2021-01-16 09:40 UTC, zolomohan commented on articles/npm-vs-npx-what-is-the-difference/index.md
> +With NPX, you just need this NPX command to execute the package.
```suggestion
To execute a package with NPX, run:
```

2021-01-16 09:40 UTC, zolomohan commented on articles/npm-vs-npx-what-is-the-difference/index.md
> +  npx [options] <command>[@version] [command-arg]...
```suggestion
Type `npx --help` to get a more detailed npx commands syntax.

Output: 
```bash
  npx [options] <command>[@version] [command-arg]...
```

2021-01-16 09:40 UTC, zolomohan commented on articles/npm-vs-npx-what-is-the-difference/index.md
> +When using NPM, you had to remember and type the package path to the command, as explained in the Eslint case.
```suggestion
When using NPM, you had to remember and type the path of the package in the command, as explained in the Eslint case.
```

2021-01-16 09:40 UTC, zolomohan commented on articles/npm-vs-npx-what-is-the-difference/index.md
> +This is tiresome to always add the node modules path, referencing them all over your files and commands.
```suggestion
It is tiresome to always add the node modules path, referencing them all over your files and commands.
```

2021-01-16 09:40 UTC, zolomohan commented on articles/npm-vs-npx-what-is-the-difference/index.md
> +
Some points are very repetitive, as the temporary cache without installing. Make sure you don't repeat points.

2021-01-16 09:40 UTC, zolomohan commented on articles/npm-vs-npx-what-is-the-difference/index.md
> +npx run db:migrate
I think you mean `npm`

2021-01-16 09:40 UTC, zolomohan commented on articles/npm-vs-npx-what-is-the-difference/index.md
> +Will be enough to seed the database.
```suggestion
Running the below command will be enough to seed the database.

```bash
npx sequelize db:seed
```
```

2021-01-16 09:40 UTC, zolomohan commented on articles/npm-vs-npx-what-is-the-difference/index.md
> +If you want to execute a specific package's version, let's say, Eslint, you don't have to install that package version in your system. All you need is to specify the package version, as shown below.
```suggestion
If you want to execute a specific package's version, let's say, Eslint, you should specify the package version, as shown below.
```

2021-01-16 09:40 UTC, zolomohan commented on articles/npm-vs-npx-what-is-the-difference/index.md
> +For example, let's take a Node.js project, for instance, where [Webpack](https://www.npmjs.com/package/webpack) installed globally, and it's currently installed version is 4.40.3. Weback is used for
```suggestion
For example, let's take a Node.js project, for instance where [Webpack](https://www.npmjs.com/package/webpack) is installed globally, and the currently installed version is 4.40.3. Webpack is used for bundling project assets. Check out this [guide](/engineering-education/webpack/) to learn more about configuring Webpack with your project. When configured, run `webpack` to get the command results.
```

2021-01-16 09:40 UTC, zolomohan commented on articles/npm-vs-npx-what-is-the-difference/index.md
> +[NVM](https://dev.to/ms314006/how-to-install-NPM-through-nvm-node-version-manager-5gif) stands for node version management. It helps you to install different Node.js versions is your computer.
```suggestion
[NVM](https://dev.to/ms314006/how-to-install-NPM-through-nvm-node-version-manager-5gif) stands for Node Version Management. It helps you to install different Node.js versions is your computer.
```

2021-01-16 09:40 UTC, zolomohan commented on articles/npm-vs-npx-what-is-the-difference/index.md
> +Moving a Node.js installation from one version to another using [NVM](https://dev.to/ms314006/how-to-install-NPM-through-nvm-node-version-manager-5gif) can a little bit tricky. NPX helps you to use s
```suggestion
Moving a Node.js installation from one version to another using [NVM](https://dev.to/ms314006/how-to-install-NPM-through-nvm-node-version-manager-5gif) can be a little bit tricky. NPX helps you to use specific Node.js versions without using NVM.
```

2021-01-16 09:40 UTC, zolomohan commented on articles/npm-vs-npx-what-is-the-difference/index.md
> +NPX will download and run the code directly from the gist.
```suggestion
NPX will download and run the code directly from a gist.
```

2021-01-16 09:40 UTC, zolomohan commented on articles/npm-vs-npx-what-is-the-difference/index.md
> +Here is a simple example of running a gist code. The gist has the main js and `package.json` files.  Let's see the NPX output. Check the code from the [Github gist](https://gist.github.com/kimkimani/
```suggestion
Here is a simple example of running a gist code. The gist has the `main.js` and `package.json` files.  Let's see the NPX output. Check the code from the [Github gist](https://gist.github.com/kimkimani/116e1e9d898169662fbaf6973bdbc3f5).
```

2021-01-16 09:40 UTC, zolomohan commented on articles/npm-vs-npx-what-is-the-difference/index.md
> +I hope this guide helps you understand the differences between NPM and NPX and understand some major use cases of NPX.
```suggestion
I hope this guide helped you understand the differences between NPM and NPX and understand some major use cases of NPX.
```

2021-01-16 13:04 UTC, kimkimani commented
@zolomohan, It should be better now.

2021-01-17 10:16 UTC, zolomohan commented
@kimkimani Can you add an Overview section with a list of all the topics you are covering in the article?

2021-01-20 18:30 UTC, hectorkambow commented
Due to the level of revision will be adding a tiered label 👍

2021-01-20 18:38 UTC, merged

2021-01-20 18:39 UTC, kimkimani commented
> Due to the level of revision will be adding a tiered label 👍

@hectorkambow

2021-01-20 18:41 UTC, kimkimani commented
> @kimkimani Can you add an Overview section with a list of all the topics you are covering in the article?

I think this review round was reviewer suggestion to add a table of content. Which in my case I have not come across as a review suggestion. @hectorkambow

2021-01-20 18:43 UTC, hectorkambow commented
> > @kimkimani Can you add an Overview section with a list of all the topics you are covering in the article?
> 
> I think this review round was reviewer suggestion to add a table of content. Which in my case I have not come across as a review suggestion. @hectorkambow

Ah - understood - I'm more referring to the changes and revisions made by the peer contributor.  

Due to the limit resources of the team - we can not provide revisions services. 

That is why we ask for the articles to polished up and publish ready. 

This means no revisions from our side (we try to be understanding and allow) - only minor (1-2) edits.