Introduction to Open Source Licenses
section-io/engineering-education pull request #1141
Opened 2021-01-02 10:52 UTC by lalith1403

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2021-01-02 10:53 UTC, lalith1403 commented
This fixes #708

2021-01-03 16:32 UTC, cyberShaw requested changes
Good one as always, @lalith1403! Please make the suggested changes so that we can move on to final review. 💯

2021-01-03 16:32 UTC, cyberShaw commented on articles/open-source-licencses/index.md
> +2. The second way is to include the markdown version of the license in a file called LICENSE.md. GitHub recognizes this file and displays the type of license on the right panel of the repository page
>  LICENSE.md

This is being recognized as a link by markdown and is redirecting to a website named license.md when I click on it. Could you please make sure this doesn't happen, perhaps by adding backticks?

```md
`license.md`
```

2021-01-03 16:32 UTC, cyberShaw commented on articles/open-source-licencses/index.md
> +
Great article, @lalith1403! One suggestion that would make this article better would be the addition of a summary table, where you compare the permissions, limitations and "ideal for" column, that discusses the licenses in a crisp manner.

2021-01-07 13:07 UTC, lalith1403 commented
@cyberShaw , I have made the requested changes. Thank you.

2021-01-07 15:18 UTC, cyberShaw commented
Thank you for making the changes, @lalith1403!

2021-01-16 02:58 UTC, hectorkambow commented
plagiarism check done

2021-01-17 20:00 UTC, merged