Implementing Linear Regression Using Gradient Descent in Python
section-io/engineering-education pull request #1172
Opened 2021-01-04 16:47 UTC by lalith1403

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

this fixes #1165

2021-01-05 16:03 UTC, hectorkambow commented
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

2021-01-21 02:27 UTC, cyberShaw requested changes
Great and crisp article, @lalith1403!

I've suggested some minor improvements to the article. Please implement those and we can move on to final review.

2021-01-21 02:27 UTC, cyberShaw commented on articles/linear-regression-code/index.md
> +In the previous article, we looked at the theory behind linear regression. In this article, we will implement the linear regression algorithm from scratch and understand the various steps involved. I
Could you add a link to the previous article?

2021-01-21 02:27 UTC, cyberShaw commented on articles/linear-regression-code/index.md
> +The training and test accuracy obtained using the [library](/engineering-education/house-price-prediction/) stands at 93% and 79.29%, respectively. We conclude that the data requires some non-lineari
```suggestion
The training and test accuracy obtained using the [library](/engineering-education/house-price-prediction/) stand at 93% and 79.29%, respectively. We conclude that the data requires some non-linearity to be introduced, and polynomial regression would probably work much better than linear regression. 
```

2021-01-21 02:27 UTC, cyberShaw commented on articles/linear-regression-code/index.md
> +
Suggestion: You could have an additional sub-heading where you define terms such as Bias, Weights, Loss, Independent Variable, Dependent Variable, etc. (Just a single line definition)

I am aware that this article is supposed to be a continuation of another article, but if a beginner to ML is reading this, a glossary would be really helpful for reference.

2021-01-21 02:27 UTC, cyberShaw commented on articles/linear-regression-code/index.md
> +import numpy as np
It would be a good idea to add comments to your code, thereby making it easier for a beginner to follow.

2021-01-21 02:27 UTC, cyberShaw commented on articles/linear-regression-code/index.md
> +print(f"X_train:{X_train.shape}\ny_train:{y_train.shape}")
Please add code comments here too :)

2021-01-22 23:57 UTC, hectorkambow commented
plagiarism check done

2021-01-24 14:45 UTC, cyberShaw commented
@lalith1403 I just went through the changes and they look great! Could you add the glossary change that I suggested and we can mark this ready for final review.

2021-01-24 14:46 UTC, lalith1403 commented
Regarding the glossary, there is a detailed article on the same, which i did mention in the prerequisites section. I did that to avoid redundancy.

2021-01-24 18:15 UTC, merged