Getting started with MATLAB
section-io/engineering-education pull request #1185
Opened 2021-01-05 12:34 UTC by ahmadmardeni1

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #947

2021-01-05 12:35 UTC, ahmadmardeni1 commented
This fixes #947

2021-01-05 16:02 UTC, hectorkambow commented
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

2021-01-07 12:04 UTC, lalith1403 commented
@ahmadmardeni1 At quick glance this seems to be an interesting article. However, I observed that the sentences were compounded therefore decreasing the readability. Can you go through the entire article and make sure the sentences are short. Use Hemmingway App for the same. I have made a few changes for your reference.

2021-01-07 12:30 UTC, ahmadmardeni1 commented
Good afternoon @lalith1403 
I used Hemmingway before submitting my PR but it didn't show me red flags except for my code. However, I did some changes, hope that it is good now.

2021-01-12 13:24 UTC, lalith1403 requested changes
I had asked you to make some changes related to readability. Refer to the changes asked. Hemingway, Grammarly only help up to a certain extent. They check for grammatical accuracies. But, the way we put across the ideas is equally important, if not more. 

Therefore, go through the comments specified. Do a thorough analysis of the comments and make changes to the article you think are similar but not mentioned. 

Refer to the content published earlier to get a feel for the type of content and explanations we expect from the authors.

2021-01-12 13:24 UTC, lalith1403 commented on articles/getting-started-with-matlab/README.md
> +In heart, MATLAB is a calculator. For example, try: `1+1`, `sqrt(4)`, or `sin(pi/2)`.
At the core of MATLAB lies efficient matrix computations. It is not a calculator.

2021-01-12 13:24 UTC, lalith1403 commented on articles/getting-started-with-matlab/README.md
> +In heart, MATLAB is a calculator. For example, try: `1+1`, `sqrt(4)`, or `sin(pi/2)`.
These commands can be through the interpreter.

2021-01-12 13:24 UTC, lalith1403 commented on articles/getting-started-with-matlab/README.md
> +If you want to output a specific range of elements, you have to reference the vector with a colon. For example:
Subheading. Slicing Operation (under Vector Heading).

2021-01-12 13:24 UTC, lalith1403 commented on articles/getting-started-with-matlab/README.md
> +Now let's learn how to create a smaller matrix from our existing one. For example, if you execute `values(:, 1:2)` the result will be:
Explain the slicing operation in detail. What is the comma doing? Why is the first value left blank? Explain these in detail. These concepts explained in-depth add tremendous value and differentiate the content from the existing ones,

2021-01-12 13:24 UTC, lalith1403 commented on articles/getting-started-with-matlab/README.md
> +Now go and execute `values(1:3, 2:4)` yourself. What will be the result?
Try executing  `values(1:3, 2:4)`. Check if you get the same result as shown below: (Display the result)

2021-01-12 13:24 UTC, lalith1403 commented on articles/getting-started-with-matlab/README.md
> +When you use `zeros` which is a built-in function, it makes every value equal to zero. For example, if you write `a = zeros(4:5)` then the result will be four rows and five columns of zeros:
it initializes a matrix of specified dimensions with values initialized to 0.

2021-01-12 13:24 UTC, lalith1403 commented on articles/getting-started-with-matlab/README.md
> +`Ones` use the same method above, it makes every value equal to one. Try `b = ones(5:6)` and see the result yourself.
The `ones` method is similar to `zeros,` except it initializes the matrix's values to 1.

2021-01-12 13:24 UTC, lalith1403 commented on articles/getting-started-with-matlab/README.md
> +`Eye` is a built-in function as well, it makes every value on the main diagonal equal to one and zeros elsewhere. Example:
`eye` is a built-in function that generates an identity matrix. An identity matrix is characterized by all diagonal elements being 1 and the non-diagonal entries equal to 0.

2021-01-12 13:24 UTC, lalith1403 commented on articles/getting-started-with-matlab/README.md
> +Linspace function generates linearly spaced vectors. The difference between colon operator and linspace is that the second one gives us control over the points. For example, if you write `linspace(1,
`linspace` generates vectors with entries spaced equidistantly. It takes in the starting point, the ending point, and the number of points as its arguments. For example...

2021-01-12 13:24 UTC, lalith1403 commented on articles/getting-started-with-matlab/README.md
> +#### M-files
Matlab files

2021-01-12 13:24 UTC, lalith1403 commented on articles/getting-started-with-matlab/README.md
> +Entering commands at MATLAB prompt is not practical when the problems will be complicated. The solution will be using M-files which is user-defined commands that normally have input & output and the
Using the MATLAB interpreter is not a wise choice for implementing and storing MATLAB code. Therefore, the code is stored in `.m` files. 

The second sentence is not clear. Change it.

2021-01-12 13:24 UTC, lalith1403 commented on articles/getting-started-with-matlab/README.md
> +Now let's create a function. First of all, you need to press on *New Script*:
Begin by clicking on _New Script_.

2021-01-12 13:24 UTC, lalith1403 commented on articles/getting-started-with-matlab/README.md
> +Second, press on *New* then *Function*:
Secondly, press on _New_ followed by _Function_

2021-01-12 13:24 UTC, lalith1403 commented on articles/getting-started-with-matlab/README.md
> +If you are familiar with the Matplotlib plotting library for Python programming language, it will be very easy for you to follow this section. However, we will explain it simply as possible.
Insert the link to the matplotlib tutorial in the eng-ed library.

2021-01-12 13:24 UTC, lalith1403 commented on articles/getting-started-with-matlab/README.md
> +First of all, let's define the t (a variable indicating time).
Don't use first of all a lot. It makes the reader lose interest. First of all should be used carefully, once or twice per article.

2021-01-12 13:24 UTC, lalith1403 commented on articles/getting-started-with-matlab/README.md
> +First of all, let's define the t (a variable indicating time).
define t... the is not needed.

2021-01-12 13:24 UTC, lalith1403 commented on articles/getting-started-with-matlab/README.md
> +This is just a *tip of the iceberg*. Change the amplitude, frequency, phase, subplot numbers, etc.. . Try it out for yourself and see the results. If you are interested more in MATLAB, keep following
You haven't mentioned anything about amplitude, frequency, and phase in the above section. Most of the readers will not be aware of these concepts. Clarify these before you code it out.

2021-01-15 16:43 UTC, ahmadmardeni1 commented
Good evening. @lalith1403 I did the changes.
But I want to point out two things
About the `Slicing Operation`, I did explain it in detail in the (97) line.
And I don't think that I need to explain what amplitude, frequency, and phase are.  It is the basic physics which anyone in school knows for sure. But please if you still think that I should explain it then just tell me.
Also if there is anything else that can improve my tutorial then just tell me. I would like to improve my writing skills based on your tips. And thank you for your time.

2021-01-15 16:50 UTC, hectorkambow commented
> Good afternoon @lalith1403
> I used Hemmingway before submitting my PR but it didn't show me any red flags except on my code. However, I did some changes, hope that it is good now.

Another option besides Hemmingway - is this one:
>https://prowritingaid.com/

Use them as guides - they are not correct 100% - but it helps improve some sentences.

2021-01-15 16:51 UTC, hectorkambow commented
> Good evening. @lalith1403 I did the changes.
> But I want to point out two things
> About the `Slicing Operation`, I did explain it in detail in the (97) line.
> And I don't think that I need to explain what amplitude, frequency, and phase are. It is basic physics (sin, cos, and tan waves) which anyone in school knows for sure. But please if you still think that I should explain it then just tell me.
> Also if there is anything else that can improve my tutorial then just tell me. I would like to improve my writing skills based on your tips. And thank you for your time.

Perhaps including some external links to help explain those "amplitude, frequency, and phase are."
That way you dont have to go into full detail about them - but the reader has the option to click through and read more on those topics.

2021-01-15 16:53 UTC, ahmadmardeni1 commented
> > Good evening. @lalith1403 I did the changes.
> > But I want to point out two things
> > About the `Slicing Operation`, I did explain it in detail in the (97) line.
> > And I don't think that I need to explain what amplitude, frequency, and phase are. It is basic physics (sin, cos, and tan waves) which anyone in school knows for sure. But please if you still think that I should explain it then just tell me.
> > Also if there is anything else that can improve my tutorial then just tell me. I would like to improve my writing skills based on your tips. And thank you for your time.
> 
> Perhaps including some external links to help explain those "amplitude, frequency, and phase are."
> That way you dont have to go into full detail about them - but the reader has the option to click through and read more on those topics.

Sure, I will do it

2021-01-15 16:59 UTC, hectorkambow commented
@ahmadmardeni1  👍  

Also please be sure to go through the older comments made by our peer reviewer to be sure we make all suggested changes to improve the article. 

Some comments become hidden after multiple comments are made on a PR (I've noticed in the past).

2021-01-15 17:02 UTC, hectorkambow commented
Just something to note as a general statement: 
When we are creating and sharing content with the community, we want to make sure that : "We want people to get content different from what was is available elsewhere online." 

Just something to keep in mind as we draft our articles. 🚀  

Keep up the great work Gents!

2021-01-15 17:04 UTC, ahmadmardeni1 commented
> Just something to note as a general statement:
> When we are creating and sharing content with the community, we want to make sure that : "We want people to get content different from what was is available elsewhere online."
> 
> Just something to keep in mind as we draft our articles. 🚀
> 
> Keep up the great work Gents!

Sure. I'm doing my best to deliver good content. And I will work harder.

2021-01-15 17:14 UTC, hectorkambow commented
plagiarism check done

2021-01-15 17:22 UTC, ahmadmardeni1 commented
> @ahmadmardeni1 👍
> 
> Also please be sure to go through the older comments made by our peer reviewer to be sure we make all suggested changes to improve the article.
> 
> Some comments become hidden after multiple comments are made on a PR (I've noticed in the past).

I did all the changes but in 3 different commits🚀

2021-01-21 17:09 UTC, merged