Getting started with classes and objects
section-io/engineering-education pull request #1250
Opened 2021-01-09 18:33 UTC by Dawe-7

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #992

2021-01-15 09:00 UTC, lalith1403 requested changes
Well written article.

2021-01-15 12:51 UTC, Dawe-7 commented on articles/getting-started-with-classes-and-objects-in-c++/index.md
> +#### What is a Class?
@lalith1403 could you explain more on this in order to make the change appropriately.

2021-01-15 13:00 UTC, lalith1403 commented on articles/getting-started-with-classes-and-objects-in-c++/index.md
> +#### What is a Class?
I meant, don't make the headings and subheadings title cased. Instead, keep the first word of the headings capital.

For example:

What is a class?

2021-01-15 13:04 UTC, Dawe-7 commented on articles/getting-started-with-classes-and-objects-in-c++/index.md
> +#### What is a Class?
Thanks for the clarification.

2021-01-15 13:14 UTC, Dawe-7 commented
@lalith1403 I've made the requested changes, kindly review.

2021-01-20 02:35 UTC, hectorkambow commented
plagiarism check done

2021-01-24 21:45 UTC, merged