Developer's Guide to Search Engine Optimization
section-io/engineering-education pull request #285
Opened 2020-09-01 15:15 UTC by lalith1403

description: A developers guide to implementing various techniques to improve website's ranking on search engines such as google.

Added a hero image as well.

2020-09-02 18:40 UTC, louisefindlay23 requested changes
Great guide, @lalith1403. I'm sure this will help developers who are new to SEO. I've pointed out a few grammar corrections and suggested some changes to aid readability.

2020-09-02 18:40 UTC, louisefindlay23 commented on articles/web-dev's-guide-SEO/index.md
> +Search engine optimization (SEO) is an incredibly important aspect of designing websites. SEO is usually tackled by the marketing department in a given company. But, developers have an equal role to
You should capitalise Assistant and revise “ Some links provide a vanilla experience with nice imagery and graphics, smooth transitions between apps, for example, LinkedIn URLs.” to be more readable. 

Perhaps something like? “Some links provide nice imagery and smooth transitions between apps such as LinkedIn URLs for example.”

2020-09-02 18:40 UTC, louisefindlay23 commented on articles/web-dev's-guide-SEO/index.md
> +Search engine optimization is the art of standing out amongst other websites. This art is pioneered by creating an experience that the user seeks repetitively, thereby increasing the presence on the
designing **a** website

lowercase metadata

2020-09-02 18:40 UTC, louisefindlay23 commented on articles/web-dev's-guide-SEO/index.md
> +Let us look at some of the ways that are used to improve SEO. These are factors responsible for ensuring crawlers can do their job easily. Earlier, the HTML meta tag was used to fill in a set of impo
The first sentence could flow better. “Let's look at some of the methods that can be used to improve SEO”

ensuring crawlers can easily do their job would flow better.

Severe exploitation of this would also aid flow.

Long sentence. Perhaps full stop after present there and then “They then list the”.

2020-09-02 18:40 UTC, louisefindlay23 commented on articles/web-dev's-guide-SEO/index.md
> +At the same time, the content plays a major role. The amount of time a user spends and the monetization capacity are tracked regularly by the crawlers. Finally, target the niche audience matters. Pro
the target niche makes more sense.

There should be a space between Experience and the bracket. 

You should replace more with a larger.

2020-09-02 18:40 UTC, louisefindlay23 commented on articles/web-dev's-guide-SEO/index.md
> +1. **Adding meta tag**: Adding meta tags is the oldest way of implementing SEO. These meta tags are placed inside the head tag along with other link tags. Let us look at examples for the same.
Add the between adding and meta.

Change to Let us look at the example below for readability.

2020-09-02 18:40 UTC, louisefindlay23 commented on articles/web-dev's-guide-SEO/index.md
> +2. **Adding title tag**: The title tag displays the current title of the webpage. A common mistake that developers make is having the same title tag for most of the pages on a website. The ranking al
Add the between adding and title.

Remove the space between” and Developer's.

Change results at to results from.

2020-09-02 18:40 UTC, louisefindlay23 commented on articles/web-dev's-guide-SEO/index.md
> +1. **Adding meta tag**: Adding meta tags is the oldest way of implementing SEO. These meta tags are placed inside the head tag along with other link tags. Let us look at examples for the same.
Consider adding a #### h4 heading for semantics for headings of this type.

2020-09-02 18:40 UTC, louisefindlay23 commented on articles/web-dev's-guide-SEO/index.md
> +3. **Adding favicons:** Favicons are the tiny icons that appear on the tabs. They don't directly affect SEO. They play a vital role in optimizing the user experience. The favicons represent the brand
You could reference the RealFaviconGenerator, https://realfavicongenerator.net as a good tool to generate favicons of required sizes.

2020-09-02 18:40 UTC, louisefindlay23 commented on articles/web-dev's-guide-SEO/index.md
> +Let us look at how these property names help enhance the user experience in a Facebook post.
You could reference Facebook's tool for validating OpenGraph meta tags. https://developers.facebook.com/tools/debug/

2020-09-02 18:40 UTC, louisefindlay23 commented on articles/web-dev's-guide-SEO/index.md
> +The ```canonicalURL``` mentioned in the meta tag is an alias for human-readable URLs. Let's understand it in detail. When we go to a link on amazon's website, we find that the page URL has the book's
You only need one backtick for inline code formatting. Three is for code blocks.

2020-09-02 18:40 UTC, louisefindlay23 commented on articles/web-dev's-guide-SEO/index.md
> +The ```canonicalURL``` mentioned in the meta tag is an alias for human-readable URLs. Let's understand it in detail. When we go to a link on amazon's website, we find that the page URL has the book's
Amazon should be capitalised. Fetched should be lowercase.

2020-09-02 18:40 UTC, louisefindlay23 commented on articles/web-dev's-guide-SEO/index.md
> +Server-side rendering enables the crawlers to get all the content including the images, videos, links, etc. Therefore, crawlers get more data to build knowledge graphs. This increases the chances of
Replace the comma after links with and.

2020-09-02 18:40 UTC, louisefindlay23 commented on articles/web-dev's-guide-SEO/index.md
> +We have looked at various methods for optimizing the websites. Accessing this information gives power to the developer to create search engine optimized sites. We hope this helps you build optimized
Remove the before websites.

2020-09-02 19:12 UTC, lalith1403 commented
> Great guide, @lalith1403. I'm sure this will help developers who are new to SEO. I've pointed out a few grammar corrections and suggested some changes to aid readability.

I have made the changes as requested! Thank you for the detailed feedback :)

2020-09-03 00:48 UTC, hectorkambow commented
Plagiarism Check DONE

2020-09-03 11:18 UTC, louisefindlay23 requested changes
Thanks for revising, @lalith1403. I'm glad you found my feedback insightful. I just noticed one small typo you need to fix before I can pass it on to tech review.

2020-09-03 11:18 UTC, louisefindlay23 commented on articles/web-dev's-guide-SEO/index.md
> +Search engine optimization (SEO) is an incredibly important aspect of designing websites. SEO is usually tackled by the marketing department in a given company. But, developers have an equal role to
You need to add a space before Some (in Some links)

2020-09-03 11:26 UTC, lalith1403 commented
> Thanks for revising, @lalith1403. I'm glad you found my feedback insightful. I just noticed one small typo you need to fix before I can pass it on to tech review.

@louisefindlay23 can you check? I have pushed the update.

2020-09-03 11:31 UTC, louisefindlay23 approved these changes
Thanks, @lalith1403.

2020-09-03 17:46 UTC, louisefindlay23 approved these changes
@damikanye, great work. I've made some minor changes and it's ready for the final review before publication. 

@hectorkambow, can you assign a final reviewer, add front-matter and change the folder name to all lowercase?

2020-09-04 00:51 UTC, merged