Building a blog from scratch using jekyll
section-io/engineering-education pull request #318
Opened 2020-09-15 19:38 UTC by geoffrey45

Written on building a static blog using Jekyll.

I've talked about:
- installing ruby and Jekyll
- Starting a new Jekyll blog
- Adding posts to the blog
- Using custom layouts
- Using includes
- Custom styling using sass

The article comes with an edited hero image from Unsplash.

2020-09-22 18:10 UTC, hectorkambow commented on articles/build-a-jekyll-site/index.md
> +Create a new fo the basics oflSer w[here](https://sass-lang.com/guide) you will be creating your blog.
started a preliminary review on your article -but I've been running into similar sentences like this - if you could revisit the article - do a full revision - checking for mistake or grammar - and improve any readability issues 🚀 

Eg: "Create a new fo the basics oflSer w[here](https://sass-lang.com/guide) you will be creating your blog."

2020-09-22 23:10 UTC, geoffrey45 commented
@hectorkambow I've checked and rectified the mistakes. I've also checked the grammar. Ready for review

2020-09-24 18:10 UTC, hectorkambow commented
👋 good afternoon Nathan - wanted to ask if you could give this "Building a blog from scratch using Jekyll" a tech review when you have a moment. 
@npwaters 
🚀  
Thank you

2020-09-28 18:25 UTC, hectorkambow commented
plagiarism check done

2020-09-30 12:18 UTC, louisefindlay23 requested changes
@geoffrey45, great article. It teaches the basics of Jekyll in an easy to understand way and despite never touching Ruby before, I could easily follow your guide. 

However, there was an issue with one of your code snippets that I couldn't run and I've made some suggestions that you should consider to improve readability and add value.

2020-09-30 12:18 UTC, louisefindlay23 commented on articles/build-a-jekyll-site/index.md
> +Let's add the hero image to your post. Add a `hero` property at the bottom of your front matter in your post markdown file.
in **one of** your markdown **files in the _posts folder** would be clearer.

2020-09-30 12:18 UTC, louisefindlay23 commented on articles/build-a-jekyll-site/index.md
> +\# default.html
You should either remove the \ and have these as Markdown headings or include the page titles as comments inside the code snippets.

2020-09-30 12:18 UTC, louisefindlay23 commented on articles/build-a-jekyll-site/index.md
> +The empty front matter in `main.css` tells Jekyll that the file should be processed. Now, import the stylesheet in `default.html`. Put the following line between the `head` tags in `default.html`.
Now, **we need** to import the stylesheet would make it clearer, you will inform the readers of how to do so.

2020-09-30 12:18 UTC, louisefindlay23 commented on articles/build-a-jekyll-site/index.md
> +> Jekyll uses [Sass](https://sass-lang.com/) stylesheet. You can learn Sass basics [here](https://sass-lang.com/guide).
stylesheet**s**. You should move this explanation to just before you mention Sass to explain this to users earlier.

2020-09-30 12:18 UTC, louisefindlay23 commented on articles/build-a-jekyll-site/index.md
> +Note that the imported stylesheet is a `css` file and not `scss`. The imported file is the processed file located at `_site/assets/css/style.css`. Reload the page to see the stylesheet at work.
You could add a little more detail here about the fact that Sass is a CSS pre-processor the reason why it needs to be processed (converted) into a CSS file (for the browser to read.)

2020-09-30 12:18 UTC, louisefindlay23 commented on articles/build-a-jekyll-site/index.md
> +To create a new post, create a markdown file and name it `2020-09-14-my-new-site.md`. Feel free to change the date and slug. If you reload your site, you can see you have a new post. If you click it
It would be beneficial to explain what Markdown is and add a brief section explaining common formatting (or link to a Markdown guide.)

2020-09-30 15:04 UTC, geoffrey45 commented on articles/build-a-jekyll-site/index.md
> +```jinja
@louisefindlay23 I couldn't find a  highlighting syntax for Liquid so I used Jinja syntax highlighting since they are similar.

2020-09-30 18:41 UTC, geoffrey45 commented
@louisefindlay23 I have made the proposed changes

2020-10-01 15:42 UTC, louisefindlay23 approved these changes
@geoffrey45, great work. Thanks for implementing the changes. Just two minor corrections and the article is ready for final review, @hectorkambow.

2020-10-01 15:42 UTC, louisefindlay23 commented on articles/build-a-jekyll-site/index.md
> +Create a `_sass` folder in your base directory and create a `main.scss` inside it. Also create a `css` folder inside the `assets` folder and create a `styles.scss`. Put the following content inside f
Put the following content inside **the** files.

2020-10-01 15:42 UTC, louisefindlay23 commented on articles/build-a-jekyll-site/index.md
> +> Jekyll uses [Sass](https://sass-lang.com/) stylesheet. You can learn Sass basics [here](https://sass-lang.com/guide).
stylesheet**s**.

2020-10-01 18:18 UTC, hectorkambow commented
@louisefindlay23 added peer reviewer line 🚀

2020-10-01 18:18 UTC, merged