Objects, Arrays m
section-io/engineering-education pull request #384
Opened 2020-09-29 10:39 UTC by geoffrey45

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? see the example [Formats here](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)
- [x] Is your article properly formatted in Markdown? - see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
- [x] Have you used the correct folder and file structure? - see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)
- [x] Is your article over 750 words?
- [x] Have you used our preferred heading structure? - [H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)
- [x] Does your article provide enough value and detail about your topic? Articles should be clear, accurate, and fully explained.
- [x] Can your article be understood by beginners? **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image? (600X400 pixels (images can be resized in paint) - also please make sure the image is from a site like www.unsplash.com)
- [x] In your PR - add a comment that states ["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278) to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - Tool: [Grammarly](https://grammarly.com)
- [x] Have you checked your article for readability? - Tool: [Hemmingway](http://www.hemingwayapp.com/)
- [ ] Have you added sources for quotes and images that aren't yours?

### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting/)
- [ ] Have you used Repl.it for your code snippets?

### Contribution Guidelines
For first-time contributors and for more details, see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)

2020-09-29 10:40 UTC, geoffrey45 commented
This fixes #357

2020-09-29 13:58 UTC, Manley12 commented
Plagiarism check done.

2020-09-29 14:22 UTC, Manley12 approved these changes
Great article! Also, great use of code block examples.

There are just a few minor revisions that should be made.

2020-09-29 14:22 UTC, Manley12 commented on articles/object-arrays-destructuring/index.md
> +Objects properties can be accessed by use of **dot notation** or **square brackets notation**.
add article "the" before "use"

2020-09-29 14:22 UTC, Manley12 commented on articles/object-arrays-destructuring/index.md
> +// acess using dot nation
fix spelling of access

2020-09-29 14:22 UTC, Manley12 commented on articles/object-arrays-destructuring/index.md
> +Objects are a data-type that has properties or preferences associated with it. If you have worked with JSON data, you have already worked with objects. Arrays are a data-type used to store related it
Try rewording the last sentence for readability. Maybe say "make up" instead of "build".

2020-09-29 16:57 UTC, geoffrey45 commented
@Manley12 I've made the edits.

2020-09-30 21:36 UTC, Manley12 requested changes
The javascript code looks good. 

This is a misstatement about how splice() works with the input indexes that should be corrected. Also, please provide an example of invalid identifiers.

2020-09-30 21:36 UTC, Manley12 commented on articles/object-arrays-destructuring/index.md
> +- When adding a property to an object using a key containing invalid identifiers.
Please provide example of invalid identifiers

2020-09-30 21:36 UTC, Manley12 commented on articles/object-arrays-destructuring/index.md
> +To add items in between other items, [splice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) method is used. The index of the items before and after
While your code will place "oranges" between the first and second fruit in the array, the indexes are not the index of the items before and after the position that you would want to add the item. Instead, the first argument is the position at which insertion/deletion is to begin and the second is the number of elements that should be deleted.

2020-10-01 10:13 UTC, geoffrey45 commented
@Manley12 I've made the proposed changes. I've made corrections to the splice() methods and also provided examples of invalid identifiers

2020-10-01 13:17 UTC, Manley12 approved these changes

2020-10-02 15:31 UTC, geoffrey45 commented
This fixes #357

2020-10-02 21:25 UTC, hectorkambow commented
👋  Good afternoon @nadivgold 

Wanted to ask if you could give this "Objects, Arrays and Destructuring in JavaScript " article a Final Tech review - feel free to include any tips you see fit to help educate our newer Peer Reviewers on the revision process and what they should be looking for moving forward. 🚀 

Thank you

2020-10-07 00:13 UTC, merged