Python Database Programming : SQLite
section-io/engineering-education pull request #442
Opened 2020-10-07 20:58 UTC by ahmadmardeni1

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you used Repl.it for your code snippets?

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

this fixes #430

2020-10-08 22:25 UTC, hectorkambow commented
👋  Good afternoon @ahmadmardeni1 
Hector here the content community manager at Section - thank you so much for your 1st article contribution. 
The article is looking great so far 🚀 
Upon running your article through our 3rd party plagiarism checker it red a few flags on a few sentences - (see attached PDF)
Please revisit the article to improve and/or properly cite and sentences that need it - for any citations please use the []() syntax to place the source within the sentence(s) being cited. 

Thank you - and feel free to reach out if you have any other questions along the way - either myself or a peer reviewer will be able to help 👍 
[Python Database Programming  SQLite #442.pdf](https://github.com/section-io/engineering-education/files/5351543/Python.Database.Programming.SQLite.442.pdf)

2020-10-09 00:08 UTC, ahmadmardeni1 commented
Thank you for your time and good afternoon 🚀 @hectorkambow 
I did the changes, please take a look at it, and I will be happy to change anything you want me to change.
but I have a question, there are some natural sentences with a red flag such as "This is just a tip of iceberg", "you are ready to go" and "you have to store" 
Should I change them too?

2020-10-15 17:14 UTC, hectorkambow commented
> Thank you for your time and good afternoon 🚀 @hectorkambow
> I did the changes, please take a look at it, and I will be happy to change anything you want me to change.
> but I have a question, there are some natural sentences with a red flag such as "This is just a tip of iceberg", "you are ready to go" and "you have to store"
> Should I change them too?

Apologies for the delayed response - no those type of sentences are fine - that tool serves as a guide. Sometimes it marks sentences that are totally fine - but its good to go through them and add any sources that may be need as a link. 

🚀

2020-10-15 17:54 UTC, ahmadmardeni1 commented
@hectorkambow  no problem. and thank you for the edits, I will pay attention to them in my next tutorial.

2020-10-15 19:23 UTC, hectorkambow commented
👋  Good afternoon Marcus - hope your week is going well.  @mhoulmiere 
Wanted to ask if you could give this "Python Database Programming: SQLite" article from one of our new contributors a tech review whenever you have a moment - it seems like a very helpful article.  Just wanted to make sure everything was accurate before we publish.
Let me know if you have any questions 
Thank you  🚀

2020-10-19 14:43 UTC, mhoulmiere commented on articles/python-database-programming-sqlite/index.md
> +SQLite is an open-source and simple database engine that allows you to create a relational database and interact with it, In general, it is very lightweight and can be used within almost all programm
Typo: There should be a period where the comma is at the end of the first sentence. "...relational database and interact with it. In general, it is very..."

2020-10-19 15:22 UTC, mhoulmiere commented on articles/python-database-programming-sqlite/index.md
> +In that example, we are searching for names in table **students** where the **ID** is less than 3, and we used **ASC** to sort the column in ascending order(from the lowest value to the highest one)
Missing period at the end of the sentence.

2020-10-19 15:22 UTC, mhoulmiere commented on articles/python-database-programming-sqlite/index.md
> +In this tutorial, we will use **DB Browser for SQLite**, you can download it from [here](https://sqlitebrowser.org/dl/)
Missing the period at the end of the sentence.

2020-10-19 15:23 UTC, mhoulmiere commented on articles/python-database-programming-sqlite/index.md
> +- Control
I would add any docs/references to corroborate this assertion or explain it in your own words.

2020-10-19 15:40 UTC, mhoulmiere commented on articles/python-database-programming-sqlite/index.md
> +When the connection is closed then a ROLLBACK will happen in the next connection to the database to any outstanding transaction. (The ROLLBACK statement cancels transaction that did any changes to th
This statement is a little confusing, you should revise to make it a bit more clear that outstanding transactions == un-committed changes. Also, the parenthesis should be removed from the ROLLBACK clarification sentence.

2020-10-19 15:48 UTC, mhoulmiere requested changes
Great job on this article! It is a great introduction to using Python to interact with SQLite DBs. I've noted a few typos and made one or two suggestions that you should consider. Overall, not much needed in terms of revisions. 

Two final suggestions (not requirements) would be to consider adding a prerequisite section to clarify what the reader should have familiarity with before reading your article and to add some more links to documentation that they can leverage if they need or would like more information.

2020-10-19 21:25 UTC, ahmadmardeni1 commented
Good evening and thank you for your time🚀 @mhoulmiere 
I did all of the changes you asked for.

2020-10-19 22:27 UTC, merged