Article Submission
section-io/engineering-education pull request #449
Opened 2020-10-08 16:28 UTC by EKahuha

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you used Repl.it for your code snippets?

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-10-08 16:33 UTC, EKahuha commented
This fixes #449

2020-10-08 18:59 UTC, hectorkambow commented
Plagiarism check done ✅

2020-10-20 19:59 UTC, hectorkambow commented on articles/Why-julia-is-slowly-replacing-python-for-machine-learning-and-data-science/index.md
> +Among the current corporate users of Julia are Aviva and BlackRock. They use this tool to calculate risks and execute time-series analysis, respectively. The Celeste project, which is based on the Ju
Links to the companies and organizations would be helpful for the reader in case they are interested to see what you are talking about.

2020-10-20 20:00 UTC, hectorkambow commented on articles/Why-julia-is-slowly-replacing-python-for-machine-learning-and-data-science/index.md
> +Unlike Julia, Python is a general-purpose language. Despite not being built purposely for data science, Python offers many advantages to machine-learning and data scientists. Python has existed for a
This sentence was a bit confusing - was not sure what it was trying to convey:
"Better is that Python is implementing some great improvements, especially to the Python interpreter."

2020-10-20 20:02 UTC, hectorkambow commented on articles/Why-julia-is-slowly-replacing-python-for-machine-learning-and-data-science/index.md
> +Python is used for a broad range of tasks. Julia, on the other hand, is primarily developed to perform machine learning and statistics tasks. Because Julia is explicitly made for high-level statistic
Wasn't quite sure what: "vanilla Julia" meant - or vanilla python - Im assuming it means (out the box) no refinements made.
Let be sure to clear this up for the audience. 🚀

2020-10-20 20:04 UTC, hectorkambow commented on articles/Why-julia-is-slowly-replacing-python-for-machine-learning-and-data-science/index.md
> +Python is used for a broad range of tasks. Julia, on the other hand, is primarily developed to perform machine learning and statistics tasks. Because Julia is explicitly made for high-level statistic
Perhap a link for this sentence: "The operand system" 
Or more of an elaboration on what "The operand system" is
Lets assume the audience is smart but has no prior experience on the subject.

2020-10-21 23:28 UTC, hectorkambow commented
> This fixes #449

@EKahuha 
I believe this should be the # of the issue it links with? 
The idea content form that was approved. 🤔

2020-10-21 23:55 UTC, EKahuha commented
> > This fixes #449
> 
> @EKahuha
> I believe this should be the # of the issue it links with?
> The idea content form that was approved.

That is true @hectorkambow

2020-10-22 00:02 UTC, hectorkambow commented
> > > This fixes #449
> > 
> > 
> > @EKahuha
> > I believe this should be the # of the issue it links with?
> > The idea content form that was approved.
> 
> That is true @hectorkambow

@EKahuha 449 is the number of this PR - what is the number of the issue it links with ?

2020-10-22 00:07 UTC, EKahuha commented
> > > > This fixes #449
> > > 
> > > 
> > > @EKahuha
> > > I believe this should be the # of the issue it links with?
> > > The idea content form that was approved.
> > 
> > 
> > That is true @hectorkambow
> 
> @EKahuha 449 is the number of this PR - I am asking what is the number of the issue it links with ?

Yes, its 449 @hectorkambow

2020-10-22 00:10 UTC, hectorkambow commented
@EKahuha  
I'm sorry making I'm not asking the questions correctly. 

Could you point me to the idea content form that was approved before you wrote this article and submitted this PR ?

2020-10-22 00:25 UTC, EKahuha commented
@hectorkambow That time we had not started to use the current Idea Content Form. But here is a screenshot of the approved topic. #449 is the number of the issue. 
![Screenshot (151)](https://user-images.githubusercontent.com/70378814/96803705-b183b680-1415-11eb-8394-cf8cc9c6c562.png)

2020-10-22 00:27 UTC, hectorkambow commented
@EKahuha Thank you so much - I was confused because I saw the "this fixes" sentence - that sentence should be the # of the idea content form not the PR being submitted (for future reference) 
👍

2020-10-22 00:28 UTC, EKahuha commented
> @EKahuha Thank you so much - I was confused because I saw the "this fixes" sentence - that sentence should be the # of the idea content form not the PR being submitted (for future reference)

Sorry for the confusion.

2020-10-23 04:09 UTC, botahamec requested changes
This is a good topic. I have two main issues though:

- This was informative, but often vague. There are times where you say that Julia is good for machine learning and data science, but then don't elaborate on why.
- I didn't mention it in any of the comments, but please put this through Hemmingway, because I noticed a lot of flags in it.

2020-10-25 01:43 UTC, hectorkambow commented
@EKahuha @botahamec 
👋  Afternoon Gentlemen,
Just wanted to get an update of this PR (just to be ready for Monday) 

If it's still being worked on by the author.? 

Is it in a preliminary review, tech review, or is it ready for final review? 🚀 (more of an FYI for my end)
Thank you

2020-10-25 01:48 UTC, botahamec commented
@hectorkambow I kinda did both at the same time. The author did make edits. I just haven't rechecked it yet. I'll do that soon

2020-10-25 13:42 UTC, botahamec requested changes
Hello @EKahuha. I'm sorry it took so long. There are still just a few issues from my last round of review. One of them might be my fault for not being clear enough. However, there are still a couple of issues here. Can you please fix those?

2020-10-25 13:42 UTC, botahamec commented on articles/Why-julia-is-slowly-replacing-python-for-machine-learning-and-data-science/index.md
> +Among the current corporate users of Julia are [Aviva](https://www.aviva.com/) and [BlackRock](https://www.blackrock.com/corporate). They use this tool to calculate risks and execute time-series anal
My comment on the words "is based on" still applies

2020-10-25 13:42 UTC, botahamec commented on articles/Why-julia-is-slowly-replacing-python-for-machine-learning-and-data-science/index.md
> +Julia is a worthy competitor to [Python](https://www.python.org/), particularly in the field of arithmetic coding. As preferred tool for developers for many years, Python is facing a threat of a mode
It should be "As a preferred tool", not "As preferred tool".

2020-10-25 13:42 UTC, botahamec commented on articles/Why-julia-is-slowly-replacing-python-for-machine-learning-and-data-science/index.md
> -Python is used for a broad range of tasks. Julia, on the other hand, is primarily developed to perform machine learning and statistics tasks. Because Julia is explicitly made for high-level statistic
I should've been more clear. I was referring to your link to the vanilla library for Python. It's not clear how that's related.

2020-10-25 13:46 UTC, botahamec commented on articles/Why-julia-is-slowly-replacing-python-for-machine-learning-and-data-science/index.md
> +The [Celeste project](https://juliacomputing.com/case-studies/celeste/), that is based on the Julia language, set a new scientific record due to its fast speed in cataloguing telescopic data for astr
My comment on the wording of "is based on" still applies

2020-10-25 21:11 UTC, EKahuha commented
Hi @botahamec 
I have updated the file.

2020-10-26 15:02 UTC, botahamec approved these changes
@hectorkambow This is ready

2020-10-26 19:20 UTC, hectorkambow commented
@botahamec  👍  Thank you v much - just FYI lets be sure to please use the appropriate labels ( the blue one when its ready for final review) just in case I missed the comments 🚀 
Looking over it now 💯

2020-10-26 19:49 UTC, hectorkambow commented on articles/Why-julia-is-slowly-replacing-python-for-machine-learning-and-data-science/index.md
> +Python is used for a broad range of tasks. Julia, on the other hand, is primarily developed to perform machine learning and statistics tasks. Because Julia is explicitly made for high-level statistic
@EKahuha 
just noticing this was not address in the article

2020-10-26 20:37 UTC, merged