Basics of Transfer Learning
section-io/engineering-education pull request #504
Opened 2020-10-20 13:08 UTC by collins-a

-Article on transfer learning as index.md
-Hero image as hero.jpg
-Image of transfer learning strategies as strategies.jpg

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-10-20 13:09 UTC, collins-a commented
This fixes #451

2020-10-22 21:04 UTC, hectorkambow commented
Plagiarism check done ✔️

2020-10-23 17:06 UTC, lalith1403 requested changes
@collins-a Amazing article. A few minor suggestions to enhance readability are given. I have also mentioned a few doubts that I got as a reader. Do let me know if you feel some of the questions are answered in the article. 

After making the requested changes, a Grammarly check would ensure minimal errors. 

I loved the part on types of transfer learning. Got me thinking, which is what is required from an article. The article should be thought-provoking and at the same time, giving the answers. Excited to read the updated article.

2020-10-23 17:06 UTC, lalith1403 commented on articles/basics-of-transfer-learning/index.md
> +Many algorithms have been proposed and implemented in medical imaging to reduce the workload of doctors. They also serve the purpose of improving the accuracy of judgment. One method involves using a
The problem statement needs some attention. Consider covid-19 detection using X-rays as an example or any other example that you find suitable. Restructure the problem statement to enhance readability.

2020-10-23 17:06 UTC, lalith1403 commented on articles/basics-of-transfer-learning/index.md
> +Another method involves the use of adversarial domain adaptation. This method is used to classify prostate histopathology whole-slide images. Adversarial domain adaptation is a method used to transfo
I feel the examples are too specific. You should take the approach of mentioning the ML algorithm and a use-case for the algorithm. As a techie will be reading this article, they will drift away from the article unless they are into medicine.

2020-10-23 18:50 UTC, hectorkambow commented on articles/basics-of-transfer-learning/index.md
> +**Feature** – an individual measurable property that is being observed. It is an attribute shared by all the independent units on that analysis is to be done.
I may have changed this - I change most which to that's  (is just more common) 
👍

2020-10-23 18:58 UTC, lalith1403 commented on articles/basics-of-transfer-learning/index.md
> +**Feature** – an individual measurable property that is being observed. It is an attribute shared by all the independent units on that analysis is to be done.
Sorry about that. I have deleted the comment. Thank you.

2020-10-27 17:08 UTC, hectorkambow commented
@collins-a  just pining you to make sure you saw the comments by our peer reviewer 🚀

2020-10-27 19:19 UTC, collins-a commented
Hey, @hectorkambow @lalith1403! Apologies for the delay, made a number of improvements to the article. Let me know if they are sufficient.

2020-10-28 14:20 UTC, lalith1403 reviewed
Great job @collins-a

2020-10-28 18:49 UTC, merged