Article Submission
section-io/engineering-education pull request #510
Opened 2020-10-21 20:02 UTC by EKahuha

This fixes #450

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-10-24 13:47 UTC, lalith1403 requested changes
@EKahuha Great job! I loved reading the software-review article. A couple of minor changes and the article should be good to go for the next round of review. Let me know once updated.

2020-10-24 13:47 UTC, lalith1403 commented on articles/tableau-vs-power-bi/index.md
> +A key strength of Tableau is its ability to support many data connectors. These include the could option, [online analytical processing (OLAP)](https://olap.com/olap-definition/), as well as big data
It's not clear what you mean by could option. Probably a typo?

2020-10-24 13:47 UTC, lalith1403 commented on articles/tableau-vs-power-bi/index.md
> +### An Overview of Power BI
Add a section indicating the various parameters this article will be comparing the software on. That will give a clean and polished introduction, to begin with.

2020-10-24 14:31 UTC, EKahuha commented
Hi @lalith1403 
File updated successfully.

2020-10-25 01:34 UTC, hectorkambow commented
plagiarism check done

2020-10-25 04:45 UTC, lalith1403 approved these changes

2020-10-25 20:19 UTC, merged