Introduction to Reinforcement Learning (RL)
section-io/engineering-education pull request #514
Opened 2020-10-22 11:30 UTC by Bayler

Fixes #387

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-10-22 11:37 UTC, Bayler commented
This Fixes #387 

Hi @hectorkambow @cyberShaw 

I have had to close the previous PR on #387 because of conflicting files issue. This is a new PR but of the same revised article Peer Reviewed by @cyberShaw

2020-10-26 13:29 UTC, Bayler commented
@cyberShaw I had to close the other PR issue due to a conflicting files issue.

2020-10-27 02:25 UTC, hectorkambow commented
Plagiarism check done ✔️

2020-10-27 16:52 UTC, hectorkambow commented
@cyberShaw I believe this PR (was an older one you had started to review) 
I believe it is ready for another prem/tech review. 
Please let me know if you would like me to re-assign any review 🚀

2020-10-28 18:44 UTC, cyberShaw commented
> @cyberShaw I believe this PR (was an older one you had started to review)
> I believe it is ready for another prem/tech review.
> Please let me know if you would like me to re-assign any review 🚀

I'll do a round of tech review on this one tomorrow 🚀

2020-11-02 22:55 UTC, hectorkambow commented
@cyberShaw 
Wanted to get a status report on this PR whenever you have a moment. 
Thank you.

2020-11-03 13:58 UTC, cyberShaw commented
> @cyberShaw
> Wanted to get a status report on this PR whenever you have a moment.
> Thank you.

I'll review it today 👍

2020-11-06 00:00 UTC, cyberShaw requested changes
This article has been great, @Bayler!
I read through it and found that there were quite a few problems with the links. Most of them weren't working. I fixed them in the commit: c348c5c. Make sure you include them properly the next time.

Also, there were quite a few spelling and grammatical mistakes that I noticed. I ran the article through Grammarly and it raised quite a few red flags. Could you please fix them and we can move on to tech review?
[https://grammarly.com](https://grammarly.com)

2020-11-06 17:05 UTC, hectorkambow commented on articles/introduction-to-reinforcement-learning/index.md
> +A reward represents the gains and losses in network performance. The reward is for taking a particular action on a particular state in the previous time instance.
This sentence was not clear:
"The reward is for taking a particular action on a particular state in the previous time instance"

The reward is given? 
I think its saying that a reward is given to an agent when they perform a particular action on a particular state in a better (or shorter amount) of time???
Not sure

2020-11-06 17:42 UTC, Bayler commented
@hectorkambow is it clearer now?

2020-11-08 22:40 UTC, hectorkambow commented
@Bayler  Thank you for the edit I will give it another review now- just FYI - this particular article has been through an extensive review from our peer reviewer as well as myself and [the payout](https://github.com/section-io/engineering-education/blob/master/new_contributors/CONTRIBUTING.md#review-approval--payment-processes) will reflect as such.
🚀 Thank you

2020-11-09 22:31 UTC, hectorkambow commented
@Bayler 
Just finishing up with your article - it was a nice article learned quite a bit - I really enjoyed the metaphors and examples to explain the concepts. 

Please be sure to go over my edits to see what can be applied moving forward. Thank you 🚀

2020-11-09 22:32 UTC, merged