added spacing
section-io/engineering-education pull request #516
Opened 2020-10-22 19:30 UTC by kenny98dev

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-10-27 02:32 UTC, hectorkambow commented
👋  Good evening @kenny98dev  and welcome to the EngEd program. 
Happy to have you join us. Thank you for contributing your 1st article. 
Upon running your PR through our 3rd party plagiarism checker it raised a few red flags (see attached) & the % was a bit higher than we typically accept.
Please revisit the article and change any underlined sentences and/or and sources where needed 🚀  
As we need to ensure we are contributing original content to the community and to our audience.
Thank you
[MongoDB vs Firebase #516.pdf](https://github.com/section-io/engineering-education/files/5442577/MongoDB.vs.Firebase.516.pdf)

2020-11-02 23:02 UTC, hectorkambow commented
Author pinged via Slack - NOTE

2020-11-09 20:09 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +the developer will have to consider the users of the application or the website.
Spacing irregularity

2020-11-09 20:09 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +the developer will have to consider the users of the application or the website.
"The developer will have to consider the users of the application of the website" => very generic. Replace instead with why databases are crucial to app development to give some context.

2020-11-09 20:10 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +2.structure of the data. Choosing the right database for an application or a website involves the developer understanding the right data structures for storage and retrieval of data. Various applicat
Check capitalization.

2020-11-09 20:10 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +1. Latency.
Formatting. Use a colon and bold the word when writing a category or definition. 

i.e.

1. **Latency**: Response time of the database...

2020-11-09 20:27 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +10gen company which is now MongoDB Inc developed MongoDB in the year 2007. The 10gen main language was server-side JavaScript.10gen company started to develop as a Platform as a service ( PAAS) produ
This doesn't make sense. You are trying to say that 10gen was the original company that developed MongoDB in 2007 and changed their name.

"10gen company" is not English. => "The company 10gen"

Capitalize Platform as a Service
Spacing around (PAAS)

What were the existing relational database systems?

What does document-oriented mean?

2020-11-09 20:27 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +1. Latency.
What are other factors in choosing a database? Overview.

2020-11-09 20:28 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +2.structure of the data. Choosing the right database for an application or a website involves the developer understanding the right data structures for storage and retrieval of data. Various applicat
...and to the end-to-end response time of the application. => doesn't make sense

"an application or a website" -> redundant, pick one and be consistent

various formats In this article => run-on

"...while highlighting its differences" -> you are talking about 2 things, should be plural

2020-11-09 20:29 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +### What is firebase
Capitalization for headers, punctuation

2020-11-09 20:29 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +### Disadvantages of using Firebase
Above you wrote "Advantages of Firebase"

Make this header parallel by removing "using"

2020-11-09 20:30 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +10gen company which is now MongoDB Inc developed MongoDB in the year 2007. The 10gen main language was server-side JavaScript.10gen company started to develop as a Platform as a service ( PAAS) produ
Why and how did they develop MongoDB? You can go into the origin story and cite your sources.

2020-11-09 20:31 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +MongoDB is an open-source document-oriented database that stores data in JSON-like formats. MongoDB makes use of documents and collections instead of using tables and rows. It supports the dynamic sc
Briefly explain what a JSON-like format entails so the reader knows why it was chosen vs. XML or other formats.

Define documents and collections.

What is dynamic schema design?

2020-11-09 20:31 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +MongoDB indexes improve search performance.
How??

2020-11-09 20:34 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +MongoDB provides a replication feature by distributing data across different machines through a replica set topology.According to [Congruent Solutions](https://www.congruentsolutions.com/blogposts/mo
Replica set topology - break down

Spacing -> "Accordingly..."

Odd capitalization + spacing -> ",A replica"

Spacing throughout??? There are no spaces after periods.

In a replica set one node-> run on, needs comma

"In a replica set one node is primary node that receives all write operations and all other nodes acts as secondaries." => what does this mean??

"Replica set can have only one primary node." -> GRAMMAR. 

The concept of why there is only one primary node is confusing - simplify.

2020-11-09 20:34 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +MongoDB supports ad-hoc queries by indexing the Binary JSON ( BSON) documents.
Spacing.

What are ad-hoc queries?

2020-11-09 20:35 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +MongoDB is considered flexible since its database is written in the C++ programming language.
What does schemaless mean? What does this have to do with flexibility?

2020-11-09 20:35 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +MongoDB's performance is high as compared to other databases due to its scalability, and it has a faster query response because of replication and indexing thus making it a better choice for real-tim
How do you define high performance? Metrics, statistics??

"and indexing thus making it a..." -> missing comma

Better choice as opposed to what?

2020-11-09 20:36 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +1. It contains heterogeneous data.
What is heterogeneous data? Of what type(s)?

2020-11-09 20:36 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +2. It provides high performance, scalability, and availability.
You mention performance + scalability briefly above but never availability. What does that mean?

2020-11-09 20:37 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +3. It can be integrated with Big Data Hadoop.
Commonly referred to as just Hadoop (not Big Data Hadoop) - what is Hadoop and why should the reader care?

2020-11-09 20:37 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +4. MongoDB's documentation has an extensive collection of literature and MongoDB tutorials for new users.
Wordy. "MongoDB has extensive documentation and tutorials for new users"

2020-11-09 20:38 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +5. MongoDB has high data security since there is no risk of SQL injection.
"high data security" = awkward phrasing. Rephrase.

Why is there no risk of SQL injection? Elaborate...

2020-11-09 20:38 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +1. There is high data consumption because of denormalization.
What is denormalization?

2020-11-09 20:39 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +2. It has no joins. We need to make many queries and join data.
How does one manually join data and why is this a disadvantage, compared to, say, SQL? How is SQL's join command implemented instead? (See $lookup command)

2020-11-09 20:39 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +3. MongoDB has a limited data size.
What is the size?

2020-11-09 20:39 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +4. Indexing and searching in MongoDB is not powerful.
Why not?

2020-11-09 20:40 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +Firebase is a cloud service provider and backend as a service company based in San Francisco, California, founded in September 2011 by James Tamplin and Andrew Lee as Envolve. It provided developers
Spacing.

You don't have to write out "Application Programming Interface(API)" multiple times. You can write it once and use API from there on. Check spacing.

You repeat "enabled the integration of online chat functionality into their website." twice - delete

2020-11-09 20:41 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +Every database has its unique features, and it is designed to provide solutions for different problems. The choice of each database depends on its benefits and drawbacks, and also the business requir
Generic. This should be a recap of the specific similarities and differences you discuss, as a summary.

2020-11-09 20:41 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +According to [GeeksforGeeks](https://www.geeksforgeeks.org/difference-between-firebase-and-mongodb/), the main differences between MongoDB  and Firebase are:
Spacing

2020-11-09 20:41 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +|---|---|
Table formatting spacing

2020-11-09 20:43 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +|MongoDB Inc developed MongoDB.| Google developed Firebase|
Parallelism

Developed by MongoDB/Developed by Google
Supports C, C#.../Supports Objective-C, Java...

etc.

2020-11-09 20:47 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +According to [Cypress](https://www.cypressoft.com/post/choose-firebase-over-backend-development/),Firebase is a toolkit and infrastructure that aims at supporting the process of building better appli
Spacing

See above comment on "applications and websites"

2020-11-09 20:47 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +Firebase is a Back-end as a service owned by Google which provides a server-less backend to app and web developers. Firebase offers a wide range of backend functionalities which include authenticatio
First sentence -> Already mentioned above

Keep second sentence.

Unclear whether those features are also in MongoDB or not

2020-11-09 20:48 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +### Differences betweeen MongoDB and Firebase
Typo

2020-11-09 20:48 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +1. Hosted solution
Capitalization

2020-11-09 20:50 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +Firebase stores its data in JSON format so managing large amounts of structured data need the developer to write powerful queries in SQL.
JSON format -> just "JSON"

Need commas before clauses i.e. "so"

"need the developer" => replace need with require

2020-11-09 20:51 UTC, sudosoph commented on articles/choosing-between-firebase-and-mongodb/index.md
> +Firebase does not allow the developer to test the database in a staging environment.
How do developers test?

2020-11-09 20:52 UTC, sudosoph requested changes
- Several spacing, capitalization, and grammatical issues.
- Missing a lot of definitions and elaborations.
- Only one source mentioned.
- Parallelism in headers and table formats require work.
- Assume the reader is a beginner and make sure to define and explain things. Needs to be more informational.

2020-11-12 00:27 UTC, hectorkambow commented
@kenny98dev just pinging you to make sure you saw our Peer reviewer notes/suggestions on how to improve the article.

2020-11-18 17:16 UTC, hectorkambow commented
Just closing PR to make room in the open PR queue. This PR can be re-opened at anytime once ready 🚀 
Thank you

2020-11-18 17:16 UTC, closed without merging