CSS-IN-JS Solutions
section-io/engineering-education pull request #518
Opened 2020-10-22 22:02 UTC by CodeLeom

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [y] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [y] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [y] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [y] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [y] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [y] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [y] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [y] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [y] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [y] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [y] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [y] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [y] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-10-23 19:22 UTC, louisefindlay23 commented
@hectorkambow, can you pre-review check this article?

2020-10-23 19:35 UTC, hectorkambow commented
plagiarism check done ✔️

2020-10-24 18:04 UTC, louisefindlay23 requested changes
@CodeLeom, good article. I've never used a CSS-in-JS solution before and find your outlook on its benefits fascinating.

The first half of your article however is confusing. It jumps between components, pages, inline and external stylesheets and CSS-in-JS.

I'd suggest reworking your article to be clearer and add more detail.

**A suggested structure:**

Start with explaining the pros and cons of CSS (in terms of both inline and external stylesheets) as well as discuss several approaches (such as using multiple files and a critical CSS approach and CSS methodologies such as BEM and SMACSS) that try to alleviate the cons (CSS files and specificity).

Then explain what web components are and how that changes CSS. 

Finally, tell the readers what CSS-in-JS is and how that's better for web components than normal CSS. 

Then the last half of your article where you discuss several CSS-in-JS solutions.

I've noted the first occurrence of each capitalisation issue. Please scour your article and correct any additional ones.

2020-10-26 13:32 UTC, CodeLeom commented
@louisefindlay23 I have re-written the Article all over. Kindly review

2020-10-27 16:10 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +Using an external stylesheet slows down the performance of your website since all CSS files referenced are loaded at once even when the page needing them is not currently rendered.
@CodeLeom, this should be mentioned and stated it is similar to Styletron's critical rendering concept that you mention later in the article.

2020-10-27 16:11 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +Applying styles to a particular tag can only be done via inline stylings, specificity to HTML elements make your code difficult to maintain, especially when applying inline styles and external style
@CodeLeom, I still suggest looking into this.

2020-10-27 16:12 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +JSS is one of the options for CSS-in-JS solutions which provides you with the flexibility of using Javascript to describe styles in your app component. It blooms on its reusability and declarative wa
Instances of this are still not corrected such as Line 24, @CodeLeom.

2020-10-27 16:13 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +With an intense focus on improving user experience, styled-components are designed to enhance CSS styling for react app components. The following are the benefits of using styled-components in your r
Please correct this, @CodeLeom such as line 77.

2020-10-27 16:13 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +2. Maintenance: As with CSS-in-JS solutions, you can maintain your CSS codebase easily and track styles affecting your component without having to check through multiple CSS files.
This still needs to be corrected, @CodeLeom.

2020-10-27 16:14 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +1. Performance: To ensure high performance, Styletron follows the critical rendering concept by generating styles when needed by the demanding components. With this, browsers only load CSS rules that
@CodeLeom, can you address this?

2020-10-27 16:16 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +Like every other CSS-in-JS library, Emotion is a performant and flexible CSS-in-JS solution. Emotion makes use of String and Object styles to write CSS in Javascript, and better it ensures improved r
@CodeLeom, and better it doesn't make sense. Please reword this.

2020-10-27 16:17 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +>Getting started with Emotions is also easy, you can follow this [guide](https://emotion.sh/docs/install) to start using Emotion in your project, and you can check out a live code of Emotion Strings
@CodeLeom, can you resolve these typos?

2020-10-27 16:20 UTC, louisefindlay23 commented
@CodeLeom, great work. Your article makes much more sense and provides more value. However, there are still several outstanding comments I've made which have yet to be resolved. Have you pushed all your changes? **See mentions I've made in the unresolved comments**

2020-10-27 16:20 UTC, louisefindlay23 requested changes
@CodeLeom, great work. Your article makes much more sense and provides more value. 

However, there are still several outstanding comments I've made which have yet to be resolved. Have you pushed all your changes? **See mentions I've made in the unresolved comments**

2020-10-27 16:22 UTC, CodeLeom commented
Will make all adjust ment and push

2020-10-29 21:41 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +JSS is one of the options for CSS-in-JS solutions which provides you with the flexibility of using Javascript to describe styles in your app component. It blooms on its reusability and declarative wa
Still seeing occurrences in line 25, 32 and 38 etc. @CodeLeom.

2020-10-29 21:42 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +With an intense focus on improving user experience, styled-components are designed to enhance CSS styling for react app components. The following are the benefits of using styled-components in your r
Still seeing this in line 87, 90 and 95 etc. @CodeLeom.

2020-10-29 21:50 UTC, louisefindlay23 requested changes
@CodeLeom, thanks for making changes. Can you make sure that words such as Javascript and react are properly capitalised: JavaScript and React?

@hectorkambow, how are we doing with revision rounds? Do you think further flow (readability) edits would be necessary before tech review?

2020-10-30 14:31 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +JSS is one of the options for CSS-in-JS solutions which provides you with the flexibility of using Javascript to describe styles in your app component. It blooms on its reusability and declarative wa
@CodeLeom, the first s in JavaScript should be capitalised. Java**S**cript

2020-10-30 14:36 UTC, louisefindlay23 requested changes
@CodeLeom, thanks for correcting React. Your occurrences of JavaScript however, still have a lowercase s. The S should be capitalised.

2020-10-30 15:10 UTC, louisefindlay23 approved these changes
Thanks for making the corrections, @CodeLeom.

2020-10-30 15:46 UTC, hectorkambow commented
@CodeLeom I can not review your article as my text editor is saying that the local branch has diverged from the remote counterpart.

I believe you need to do a rebase and/or keep your fork up to date. 
Please see the instructions below:

>then use this every time before contributing a new article to keep it up to date
git fetch section

git pull --rebase section master

git push origin

Here is a link to a short video further explaining what a pull request is and how to fork a Github repository.

2020-10-30 15:47 UTC, hectorkambow commented
Another option is to close this PR and copy and paste the .md file and open a new (clean) PR 🚀

2020-10-30 16:11 UTC, louisefindlay23 requested changes
@CodeLeom, I've made a series of suggested changes to improve the flow and readability of your article. Please consider and implement them to get your article approved on to the next stage.

2020-10-30 16:11 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +CSS-in-JS is the best styling technique to settle for in the development of web applications with web components. But, this doesn’t render CSS redundant because it certainly does have its pros and it
**Flow edit**: best styling technique to **use** with web components

Remove its before cons.

2020-10-30 16:11 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +2. Reduction in Redundancy: With inline styles, you can avoid redundant code and only declare CSS styles to a particular element when needed, this way, all extraneous code stays out of the code and a
Add a line break after key.

**Flow edit:** all extraneous code **is removed.**

2020-10-30 16:11 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +3.  External stylesheet: Inline-styles aren't the only golden property of CSS.  External stylesheet keeps your codebase organized and allows you to store all CSS code within a single file and referen
Inline-styles aren't the only **way to write CSS.**

External stylesheet**s**

reference them in **webpages** that need them.

2020-10-30 16:11 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +Overriding styles is a bit of an issue without the !important keyword. When you use inline styles and try to override them in your stylesheet,  you can't do that without using the !important keyword.
You should explain why using the !important keywords is frowned upon.

2020-10-30 16:11 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +
browser**s** accessing the website

2020-10-30 16:11 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +With an intense focus on improving user experience, styled-components are designed to enhance CSS styling for React app components. The following are the benefits of using styled-components in your a
Add a line break here above.

2020-10-30 16:11 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +* Performance: To ensure high performance, Styletron follows the critical rendering concept by generating styles when needed by the demanding components. With this, browsers only load CSS rules that
in **one** go. Please fix this, @CodeLeom since I've already mentioned it previously.

2020-10-30 16:11 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +within your component, providing the same experience as using inline styles but all in CSS-in-JS solutions.
within shouldn't be on a seperate line from the previous word.

2020-10-30 16:11 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +within your component, providing the same experience as using inline styles but all in CSS-in-JS solutions.
in **a** CSS-in-JS

2020-10-30 16:11 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +Emotion took into consideration approaches taken by other CSS-in-JS solutions like styled-components and glamor, so you tend to enjoy the same benefit as them. However, despite the foundation of exis
It would bre great to add links to styled-components and glamor.

2020-10-30 16:11 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +In favor of performance, Material UI uses JSS as its core, which ensures speedy compilation from JS to CSS both at runtime and server-side. Material UI is small in size, occupying just 15kb gzipped s
I don't see a link to a guide here?

2020-10-30 16:11 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +CSS-in-JS changes the perspective of web application development from specificity to modularity, and towards implementing CSS-in-JS aptly, you now have a list of preceding CSS-in-JS solutions for web
**Flow edit:** modularity. You now have a list of modern CSS-in-JS solutions you can use in combination with web components with links to get you started.

2020-11-02 12:40 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +The traditional way of building web applications would require creating multiple CSS, JavaScript and HTML files that have a dropdown and navigation menu as a feature. This methodology of building web
@CodeLeom, you should reword this section to make it clearer to readers. I've provided an example above.

2020-11-02 12:41 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +Styling elements has been the underlying factor for the appeal of frontend web applications, and with it comes a clear understanding of web components and how it relates to CSS.
You should consider this, @CodeLeom.

2020-11-02 12:43 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +This gap in the simplification of your codebase concerning your CSS files is why you need to seek out means of encapsulating your CSS code within your JavaScript files, rather than creating external
@CodeLeom, you should remove the "This gap in the simplification paragraph" with this suggestion.

2020-11-02 12:46 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +3.  External stylesheet: Inline-styles aren't the only golden property of CSS.  External stylesheet keeps your codebase organized and allows you to store all CSS code within a single file and referen
External stylesheets **keep** your codebase

Remove s in keeps

2020-11-02 12:47 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +With an intense focus on improving user experience, styled-components are designed to enhance CSS styling for React app components. The following are the benefits of using styled-components in your a
@CodeLeom, you should add a line break after components.

2020-11-02 12:48 UTC, louisefindlay23 commented on articles/css-in-js-solutions/index.md
> +within your component, providing the same experience as using inline styles but all in CSS-in-JS solutions.
**solution**

Drop the s in solutions.

2020-11-02 12:50 UTC, louisefindlay23 requested changes
Thanks for making the changes, @CodeLeom. However, there's still one or two you need to make and some minor edits based on them.

2020-11-02 18:42 UTC, hectorkambow commented
@CodeLeom 
@louisefindlay23 
I will be closing this PR - it has a conflict on my end - and I can not check it our for review. 

@CodeLeom  please take the polished article a re-submit a new clean PR so we can check out your PR for review thank you 👍 

Please be sure to include all the suggestions made by our peer reviewer. 
Also FYI any future article of this quality (or requires this many edits and revisions) will be closed after two revisions. 

As stated in our [payout structure.](https://github.com/section-io/engineering-education/blob/master/new_contributors/CONTRIBUTING.md#review-approval--payment-processes)

2020-11-02 18:42 UTC, closed without merging