The Role of Artificial Intelligence for Smarter Cybersecurity
section-io/engineering-education pull request #585
Opened 2020-11-04 17:08 UTC by EKahuha

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-11-04 17:17 UTC, EKahuha commented
This fixes #540

2020-11-05 13:22 UTC, lalith1403 requested changes
@EKahuha Good article. I feel the article is structured well. However, we need to provide more information to the user. I have mentioned a few places where additional information will help deliver tremendous value to the reader.

Excited to read the updated article.

2020-11-05 13:22 UTC, lalith1403 commented on articles/the-role-of-artificial-intelligence-for-smarter-cybersecurity/index.md
> +Network security mainly focuses on the understanding of network topography and creating a security policy of an organization. Securities policies can help to distinguish legitimate network connection
Securities policies can help to-> Security policies help distinguish

2020-11-05 13:22 UTC, lalith1403 commented on articles/the-role-of-artificial-intelligence-for-smarter-cybersecurity/index.md
> +Often, some organizations may not have a precise naming convention for workloads and applications. This means that network security teams have to spend significant time attaching different workloads
Can you clarify the situation in a bit more detail? I want to understand how did we land at precise naming conventions and how that affects security policies? 

Some information is needed for better flow between the previous and current paragraph.

2020-11-05 13:22 UTC, lalith1403 commented on articles/the-role-of-artificial-intelligence-for-smarter-cybersecurity/index.md
> +Organizations can deploy artificial intelligence technology in their data centers to enhance data security. To ensure data security, AI essentially learns normal network behavior. It then detects cyb
I feel we are describing the role of AI very vaguely here. What are normal patterns of behavior? How are they defined? What type of AI solves this? As a reader, I want to know as much as possible from the article. 

Any person reading this knows about AI being used everywhere. What the reader might lack will be the field-knowledge. If you can talk about detecting shady behavior using an RNN or rule-based expert systems, it adds more value to the reader.

2020-11-05 13:22 UTC, lalith1403 commented on articles/the-role-of-artificial-intelligence-for-smarter-cybersecurity/index.md
> +In this case, AI is essential to identify abnormalities, outliers, and patterns in all data without the need for applying fixed rules. Human analysts depend on this output for investigation and actio
Again saying AI is performing threat hunting and passing it down to the security team is on the surface-level, What we want to provide the reader with is value. How is AI performing threat hunting? Give an intuitive example, if possible. I am not asking you to describe the algorithm in detail. But what algorithms are we talking about and how do they fit in the overall problem of threat hunting.

2020-11-05 13:22 UTC, lalith1403 commented on articles/the-role-of-artificial-intelligence-for-smarter-cybersecurity/index.md
> +Every year, there are many reported vulnerabilities to cybersecurity. It is extremely difficult to manage these unique vulnerabilities with traditional technology or human resources. Systems that use
How is vulnerability different from threat hunting? I feel we are emphasizing the point that AI solves the problem. But, as a reader, I don't understand how is it working? Divide the explanation into the following steps:
1. Problem statement: What are we trying to solve?
2. How is AI solving it(mention a few algorithms, techniques, models, if any)?
3. Advantages of AI over other systems
4. How AI integrates with the problem and solves it.

2020-11-05 13:22 UTC, lalith1403 commented on articles/the-role-of-artificial-intelligence-for-smarter-cybersecurity/index.md
> +The future of the application of artificial intelligence to improve cybersecurity looks promising. Security teams expect AI to enhance and respond better to cyber-attacks. Human analysts are designin
response speed -> response time.

2020-11-09 18:08 UTC, hectorkambow commented
plagiarism check done

2020-11-11 19:02 UTC, EKahuha commented
@lalith1403 I have updated this article.

2020-11-12 08:18 UTC, lalith1403 approved these changes

2020-11-12 16:45 UTC, hectorkambow commented
@EKahuha 
Was wondering if you had any other sources to add to this article. I only see two ? 

Where was all this information sourced from.? 

We'd like to add all the sources under a Addtional resources section.

2020-11-12 17:18 UTC, EKahuha commented
> @EKahuha
> Was wondering if you had any other sources to add to this article. I only see two ?
> 
> Where was all this information sourced from.?
> 
> We'd like to add all the sources under an Addtional resources section.

@hectorkambow 
Here are other resources: 
1. blog.eccouncil.org/the-role-of-ai-in-cybersecurity/#:~:text=Combining%20the%20strength%20of%20artificial,resulting%20in%20reduced%20response%20times.
2. https://www.balbix.com/insights/artificial-intelligence-in-cybersecurity/
3. https://itchronicles.com/security/how-ai-is-changing-the-cybersecurity-landscape/

2020-11-12 17:27 UTC, hectorkambow commented
@EKahuha  
Thank you v much. 

Lets be sure to add all our sources in future articles (we prefer them as links within the article - like you have done). 

Just adds more credibility and if someone wants more info they can easily get to it.

2020-11-12 17:30 UTC, EKahuha commented
> @EKahuha
> Thank you v much.
> 
> Lets be sure to add all our sources in future articles (we prefer them as links within the article - like you have done).
> 
> Just adds more credibility and if someone wants more info they can easily get to it.

Noted. Thank you @hectorkambow

2020-11-13 00:13 UTC, hectorkambow commented
👋  Good evening/morning Jason, 

Wanted to ask if you could give this "Artificial Intelligence for Smarter Cybersecurity" article a review? 
It's been reviewed by one of our peer reviewers - but I saw the Security aspect - and thought it could use the Wise 👁️ of @jstangroome  regarding anything we may have missed before we publish. 

Thank you v much 🚀

2020-11-13 03:05 UTC, jstangroome approved these changes
Looks good to me

2020-11-13 16:51 UTC, merged