Basics of Convolution Neural Networks
section-io/engineering-education pull request #601
Opened 2020-11-08 13:57 UTC by Bayler

Fixed #493

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-11-08 13:59 UTC, Bayler commented
This Fixes #493

2020-11-09 18:26 UTC, hectorkambow commented
Plagiarism check done

2020-11-09 18:54 UTC, lalith1403 requested changes
@Bayler, I feel a lot of content is missing. An introductory article on CNNs needs to go in-depth into the workings of the convolution operation. Moreover, by reading this, the person should understand what CNN is. Currently, the structure of the article is skewed towards ensuring all definitions are included. 

It would be best if you grasped the attention of the reader. Why do we need CNNs?
How are CNNs better than other algorithms? And then start with neural networks and convolution operation. Then strides, pooling, etc. Finally, end at using various optimizers to update the network to minimize/maximize objective accordingly.

The applications for NLP and image captioning need to be explained in depth.

2020-11-09 18:54 UTC, lalith1403 commented on articles/basics-of-convolution-neural-networks/index.md
> +A hyperparameter is also a placeholder, but unlike the parameter, hyperparameters need to set before training starts. The learning rate is one of the important hyperparameters that need to be set bef
It is important to specify that hyper-parameters can be modified as the model learns.

2020-11-09 18:54 UTC, lalith1403 commented on articles/basics-of-convolution-neural-networks/index.md
> +3. Kernel
This definition seems to be a bit off. Kernels are learned during the training process. Convolution is an operation performed on the image with the kernel in the first layer. The convolved image is convolved with kernels in the second layer, and so on.  

You mention learnable parameters. How are they different from the first point?

2020-11-09 18:54 UTC, lalith1403 commented on articles/basics-of-convolution-neural-networks/index.md
> +Stride refers to the number of pixels a convolution filter moves. It can be compared to a sliding window. The image below shows the stride, S moving with a pixel of 2
I don't think it is wise to mention the convolution filter initially. Explain convolution first, and then move onto these definitions.

2020-11-09 18:54 UTC, lalith1403 commented on articles/basics-of-convolution-neural-networks/index.md
> +### What is Convolution Neural Networks (CNN)?
What is -> What  are

2020-11-09 18:54 UTC, lalith1403 commented on articles/basics-of-convolution-neural-networks/index.md
> +Convolution Neural Networks (CNN) is a class of deep learning techniques popularly use to solve computer vision tasks.
Convolution Neural Networks (CNNs) are a

2020-11-09 18:54 UTC, lalith1403 commented on articles/basics-of-convolution-neural-networks/index.md
> +CNN learns the spatial features of inputs through a process known as backpropagation, as we will see in the image below. Backpropagation can be described as the backward propagation of errors. It is
Factual error: CNN learns the spatial features through convolution operation. Backpropagation is used to update the weights and minimize/maximize the objective function.

2020-11-09 18:54 UTC, lalith1403 commented on articles/basics-of-convolution-neural-networks/index.md
> +
Mention the convolution operation. It is essential to explain the feature extraction part.

2020-11-09 18:54 UTC, lalith1403 commented on articles/basics-of-convolution-neural-networks/index.md
> +ReLU is the default activation function when working with CNNs, as it tends to have a faster training time.
It is widely used but need not be the default one.

2020-11-09 18:54 UTC, lalith1403 commented on articles/basics-of-convolution-neural-networks/index.md
> +It is important to note that a 2 x 2 filter size applied with a stride of 2 is the most used in CNN.
Take an example and explain the same. What are the initial dimensions, and how they are reduced using pooling operation?

2020-11-09 18:54 UTC, lalith1403 commented on articles/basics-of-convolution-neural-networks/index.md
> +Recently, CNN has been used for image captioning. Here, the goal is to generate a sentence that describes the semantic content in an image. It is achieved by combining CNN with a [Recurrent Neural Ne
I feel some more explanation is required here. A beginner will find it difficult to understand how an RNN is getting fixed to a CNN.

2020-11-09 18:54 UTC, lalith1403 commented on articles/basics-of-convolution-neural-networks/index.md
> +As for text classification, texts are first converted into vectors. These vectors are then passed as inputs to the CNN. In a forward propagating manner, these vectors pass through the convolution and
Mention word vectors.

2020-11-10 04:58 UTC, Bayler commented
Noted @lalith1403 I'll make those revisions

2020-11-13 18:33 UTC, lalith1403 approved these changes

2020-11-15 19:41 UTC, merged