House Price Prediction using Machine Learning
section-io/engineering-education pull request #613
Opened 2020-11-09 17:37 UTC by lalith1403

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-11-09 17:38 UTC, lalith1403 commented
This fixes #474

2020-11-12 01:22 UTC, hectorkambow commented
Plagiarism check done

2020-11-22 16:38 UTC, adrianmurage commented
Hi @lalith1403
I'll be conducting the review in two stages:
- Preliminary review where I'll look out for: grammar, spelling, and readability
- Tech Review where I'll look out for: technical accuracy, beginner-friendliness, and currency

2020-11-23 13:30 UTC, adrianmurage requested changes
The article reads well. Great job @lalith1403.
Make the minor changes I have highlighted as I move on to the tech review.

2020-11-23 13:30 UTC, adrianmurage commented on articles/house-price-prediction/index.md
> +Another useful evaluation metric is the `Mean Squared Error`. The MSE loss gives an estimate of how far the prediction is from the mean of the output. Computing the MSE gives us an idea about the per
Consider adding the abbreviation next to the text to explicitly relate them:
`Mean Squared Error`(MSE)

2020-11-23 13:30 UTC, adrianmurage commented on articles/house-price-prediction/index.md
> +We'll begin with loading the data. Since we are using an inbuilt dataset, we'll be calling the `load_boston` function from the `sklearn.datasets` module. The data is loaded into the `data` variable.
Consider changing the preposition "with" It should be:
"We'll begin by loading the data."

2020-11-23 13:30 UTC, adrianmurage commented on articles/house-price-prediction/index.md
> +![output](/engineering-education/house-price-prediction/output.jpg)
You could consider copy-pasting the terminal output and placing it in a code fence with bash as the language.

2020-11-23 13:50 UTC, lalith1403 commented on articles/house-price-prediction/index.md
> +2. [Introduction to Supervised Learning Algorithms using Scikit-Learn](/engineering-education/supervised-learning-algorithms/)
This will work when published. It is a relative link.

2020-11-23 14:06 UTC, adrianmurage commented on articles/house-price-prediction/index.md
> +2. [Introduction to Supervised Learning Algorithms using Scikit-Learn](/engineering-education/supervised-learning-algorithms/)
Right... like images.
Thanks for pointing that out

2020-11-23 14:35 UTC, adrianmurage requested changes
@lalith1403 
I ran into a syntax error that I have highlighted here
But once fixed the code runs well

Once you make the changes, ping me
I'll do one last read and label the article ready for final review

2020-11-23 14:35 UTC, adrianmurage commented on articles/house-price-prediction/index.md
> +from sklearn. pre-processing import LabelEncoder
syntax error

2020-11-23 19:43 UTC, adrianmurage approved these changes

2020-11-23 19:44 UTC, adrianmurage commented
@lalith1403 Great job!
@hectorkambow this article is ready for final review

2020-11-23 21:15 UTC, merged