Implementing MVVM architecture in android using Kotlin #559
section-io/engineering-education pull request #620
Opened 2020-11-10 08:15 UTC by WanjaMIKE

Implementing MVVM architecture in android using Kotlin

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-11-13 11:04 UTC, kayere commented
Hello @WanjaMIKE, this a great topic. I will be reviewing your article. The review process involves two phases. I will be checking at grammar and readability in the first phase. The second phase involves checking for technical accuracy. As I go through the first review, please make sure to add your author details.

2020-11-13 18:16 UTC, WanjaMIKE commented
okay, thank you

2020-11-13 21:32 UTC, hectorkambow commented
plagiarism check done

2020-11-14 03:38 UTC, WanjaMIKE commented
Okay

2020-11-15 11:59 UTC, kayere requested changes
@WanjaMIKE - I have done a preliminary review on your article. Grammar and readability is fair. I have made some syntax and readability changes. I have also suggested some changes for you to make. The article has a lot of passive voice use and some few hard to read sentences. I have fixed some of them for you. Use [Hemingway](http://www.hemingwayapp.com/) to identify and fix the rest. Make the changes so that we can proceed to the tech review. Don't forget to pull the changes I have made first.

2020-11-15 11:59 UTC, kayere commented on articles/implementing-mvvm-architecture-in-android-using-kotlin/index.md
> +Create the app model. This is also referred to as the data class. To avoid confusion, create a package named model inside the java folder. Then, create a data class named Blog in the model package as
Rephrase the last sentence to this "There is no need to add getters and setters, Kotlin adds them to the class automatically." It is shorter and also eliminates the use of passive voice.

2020-11-15 11:59 UTC, kayere commented on articles/implementing-mvvm-architecture-in-android-using-kotlin/index.md
> +Open `activity_main.xml` file and change the layout from constraint to linear layout. Ensure that the orientation is set to vertical. This ensures that the UI components such as buttons and text view
Replace "This ensures that the UI components... " with "This arranges UI components vertically in the Layout.". It easier to read.

2020-11-15 11:59 UTC, kayere commented on articles/implementing-mvvm-architecture-in-android-using-kotlin/index.md
> +A `RecyclerView` adapter is responsible for binding the `item.xml` layout to the `RecyclerView`. It also takes in a list of items and displays them to the user. The code for the `RecyclerView` adapte
Replace " is responsible for" with "handles"

2020-11-15 12:26 UTC, WanjaMIKE commented
Okay, thank you

2020-11-15 12:54 UTC, WanjaMIKE commented
Changes fixed

2020-11-15 13:35 UTC, kayere commented
> Changes fixed

I can't see the changes. Please make sure you push your commit.

2020-11-15 17:17 UTC, WanjaMIKE commented
I have pushed the file. thanks

2020-11-16 09:18 UTC, kayere reviewed
@WanjaMIKE - I have gone through the tech review, and I have some suggestions. Please use code snippets rather than images. This allows readers to copy your code. The other suggestion is on the inline comment. Make the changes and the article will be good to go.

2020-11-16 09:22 UTC, kayere commented
*Note* - Don't forget to add the Author details on your next commit.

2020-11-17 07:29 UTC, WanjaMIKE commented
Okay I have made changes

2020-11-17 07:32 UTC, kayere commented
> Okay I have made changes

Push your commit.

2020-11-17 08:27 UTC, WanjaMIKE commented
> > Okay I have made changes
> 
> Push your commit.

I have

2020-11-17 08:40 UTC, kayere reviewed
@WanjaMike - I am almost done with the Tech review, but I have one last suggestion. Please explain what the functions in the `MainActivity` class do.

2020-11-17 09:13 UTC, kayere approved these changes
@hectorkambow - I am done with the Tech review for this article. Please give it a final review.

2020-11-17 17:17 UTC, hectorkambow commented
@WanjaMIKE  great 1st article - it looks like it will be a helpful addition to our EngEd community - please go over any of the feedback (or changes) made by the peer reviewers and/or myself to see how we can apply that same level of quality to all future articles 🚀 
Article will be published momentarily  👍

2020-11-17 17:18 UTC, hectorkambow commented
@kayere  👍  Thank you for the great review 🚀  keep up the great work.

2020-11-17 17:19 UTC, WanjaMIKE commented
Okay, thank you

2020-11-17 17:27 UTC, merged