Dive into Batch scripting language
section-io/engineering-education pull request #635
Opened 2020-11-12 17:42 UTC by ahmadmardeni1

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-11-12 17:43 UTC, ahmadmardeni1 commented
this fixes #599

2020-11-16 18:54 UTC, hectorkambow commented
plagiarism check done

2020-11-20 16:22 UTC, botahamec requested changes
General comments:

* This was an accurate introduction Batch
* The spelling and grammar need work. It's not as bad as some articles I've reviewed, but still not very good.
* Some of the examples aren't very useful, and will be hard for the reader to actually run. Please change those
* Some parts of the article need further explanation, because they aren't very clear.
* I'm not sure if you ran this through Hemmingway. There are multiple things that Hemmingway highlights that I can see being improved. Please check it again.

2020-11-20 16:22 UTC, botahamec commented on articles/dive-into-batch-scripting language/index.md
> +By default, when you run a **Batch** file it displays every command is currently executing, in order to turn off this display you have to use:
This should be two sentences

2020-11-20 16:22 UTC, botahamec commented on articles/dive-into-batch-scripting language/index.md
> +If you write a sequence of **Batch** commands and save the file with the extension **.bat** or **.cmd** then the file is called **Batch file**.
This last sentence can be shortened significantly. In fact, many of your sentences can. Did you use Hemingway to check your writing?

2020-11-20 16:22 UTC, botahamec commented on articles/dive-into-batch-scripting language/index.md
> +The execution process of a **Batch** file is line-by-line. However, you can use "goto" command which gives you the capability to jump into a particular section of your code.
**the** "goto" command

2020-11-20 16:22 UTC, botahamec commented on articles/dive-into-batch-scripting language/index.md
> +- Major **time saving**.
It should also be "savings" not "saving"

2020-11-20 16:22 UTC, botahamec commented on articles/dive-into-batch-scripting language/index.md
> +We used "@" sign to made the command apply to itself too.
It should be "**the** @ sign"

2020-11-22 06:43 UTC, ahmadmardeni1 commented
Hello @botahamec 
Thank you for your suggestions, I did the changes.
The tutorial I submitted was an old one(before I used Grammarly), sorry, my bad.
A few things I want to mention:
- The code you used will not work because it didn't work with the env variable, you can try :
```
@echo off
set ahmad123
If %ERRORLEVEL% == 1 (echo error)
```
It will display "error" because the variable name is not found.

- I didn't explain "if" because it is very clear for any programmer ( one of the Prerequisites was "A good understanding of any programming language")
Thank you again and I will take this suggestion to my next tutorials as well.

2020-11-23 15:54 UTC, botahamec commented
@ahmadmardeni1 You should put that code you just gave me in the article, because the reader needs to know that

2020-11-23 20:22 UTC, ahmadmardeni1 commented
Done @botahamec

2020-11-24 23:24 UTC, merged