Securing AI Systems from Adversaries
section-io/engineering-education pull request #636
Opened 2020-11-12 20:11 UTC by collins-a

Included article as index.md
hero image as hero.jpg
matrix image as matrix.jpg
boundary image as boundary.jpg
miscategorization image as miscategorization.png

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-11-12 20:13 UTC, collins-a commented
This fixes #600

2020-11-17 15:22 UTC, lalith1403 requested changes
Very well written article. A few minor changes, and this should be ready for the final round of review. Cheers.

2020-11-17 15:22 UTC, lalith1403 commented on articles/securing-ai-systems-from-adversaries/index.md
> +PATE works on the principle that involves training several models on disjoint data. These models are referred to as “teacher” models. If these models agree on input, no confidential details from thei
What do you mean by these models agree on input? It's not clear how they reach the same conclusion. If the models are trained on dis-joint data, then how will they reach the same conclusion? Is it happening batch-wise?

2020-11-17 15:22 UTC, lalith1403 commented on articles/securing-ai-systems-from-adversaries/index.md
> +##### Defense
Is this defense for model skewing or poisoning attacks? Mention the same.

2020-11-19 00:57 UTC, hectorkambow commented
plagiarism check done

2020-11-19 10:56 UTC, collins-a commented
Hey, @lalith1403 I've made the requested minor tweaks.  If they suffice, see you next article. Cheers!

2020-11-19 18:09 UTC, merged