Django crud api
section-io/engineering-education pull request #664
Opened 2020-11-17 14:24 UTC by paulodhiambo

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-11-17 14:27 UTC, paulodhiambo commented
Fixes #557

2020-11-18 02:18 UTC, hectorkambow commented
👋  Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

2020-11-22 16:35 UTC, adrianmurage commented
@hectorkambow 
Kindly run a plagiarism check on this

2020-11-22 16:37 UTC, adrianmurage commented
Hi @paulodhiambo 
I'll be conducting the review in two stages:
- Preliminary review where I'll look out for: grammar, spelling, and readability
- Tech Review where I'll look out for: technical accuracy, beginner-friendliness, and currency

2020-11-22 18:49 UTC, hectorkambow commented
plagiarism check done

2020-11-25 15:25 UTC, adrianmurage requested changes
Hi @paulodhiambo, great article. I have left some grammatical and readability changes you should consider making.
I'll go ahead and start reviewing the technical correctness of the article as you make them.

2020-11-25 15:25 UTC, adrianmurage commented on articles/django-crud-api/index.md
> +Lets create out django-todo project now by running the command `django-admin startproject django_todo`
Inconsistency in the project naming
"django-todo" and "django_todo" pick one and use it consistently

Also correct 
"Let's create our..."

2020-11-25 15:25 UTC, adrianmurage commented on articles/django-crud-api/index.md
> +To create an SQLite database and Todo table in the database, we will run the command `./manage.py makemigrations` to create SQL queries that will be used to create a `Todo` table in the database. To
The idea around migrations is a little confusing, even for me. Consider pointing the reader to the [migration docs](https://docs.djangoproject.com/en/3.1/topics/migrations/).
Then rewrite these as sequential steps like so:

To make migrations run:
`./manage.py makemigrations`

To apply the migrations run:
`./manage.py migrate`

2020-11-25 15:25 UTC, adrianmurage commented on articles/django-crud-api/index.md
> +In the `todo` app directory in the `views.py` file, we need to write in the logic for the CRUD functionality for our app. Django Rest framework comes with inbuilt classes which make building the CRUD
Consider rearranging this to:
"In the `views.py` file in our `todo` app directory, we are going to write the logic for the CRUD functionality for our app."

2020-11-30 14:14 UTC, adrianmurage requested changes
@paulodhiambo 
Great article. I have pointed out a few improvements.
Kindly make them and when you're done ping me, I'll go over the article one last time and mark it ready for final review

2020-11-30 14:14 UTC, adrianmurage commented on articles/django-crud-api/index.md
> +Making a GET request to http://localhost:8000/api/v1/todo in postman returns a list of `todos`.
I feel like you should point out that the server should be running.
Consider addding an instruction to run the command that runs the server.

2020-11-30 14:14 UTC, adrianmurage commented on articles/django-crud-api/index.md
> +Making a GET request to http://localhost:8000/api/v1/todo in postman returns a list of `todos`.
There was no todo items added by this point in the article.
Making a GET request returns an empty list

2020-11-30 14:14 UTC, adrianmurage commented on articles/django-crud-api/index.md
> +Making a GET request to http://localhost:8000/api/v1/todo in postman returns a list of `todos`.
I suggest you re-order the requests:
1. POST
2. GET
3. PUT
4. DELETE

2020-11-30 14:14 UTC, adrianmurage commented on articles/django-crud-api/index.md
> +Making a GET request to http://localhost:8000/api/v1/todo in postman returns a list of `todos`.
Also consider adding images with the various operations on Postman to help the reader identify what they need to be doing if they happen to be unfamiliar with postman

2020-11-30 16:34 UTC, paulodhiambo commented
@adrianmurage I am done with the suggested changes.

2020-11-30 17:34 UTC, adrianmurage approved these changes
@paulodhiambo Great job with this!
@hectorkambow this article is ready for final review

2020-12-01 20:54 UTC, merged