Secured Deep Learning in Remote Devices
section-io/engineering-education pull request #666
Opened 2020-11-17 19:30 UTC by srishilesh

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #644

2020-11-18 02:18 UTC, hectorkambow commented
👋  Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

2020-11-18 16:10 UTC, lalith1403 commented
Good morning @hectorkambow . The front matter is included. Just checking if you added it?

2020-11-19 00:58 UTC, hectorkambow commented
> Good morning @hectorkambow . The front matter is included. Just checking if you added it?

No Sir - I did not. 👀

2020-11-19 01:18 UTC, hectorkambow commented
plagiarism check done

2020-11-22 17:08 UTC, lalith1403 requested changes
@srishilesh An amazing article. I loved experimenting with the code. Some minor modifications and this should be good to go. Well done. 

The minor modifications need to be performed throughout the article. I haven't specified all the instances to keep the number of comments concise. Find all such occurrences and change it accordingly.

2020-11-22 17:08 UTC, lalith1403 commented on articles/secured-deeplearning-in-remote-devices/index.md
> +#### Initializing Neural networks for each remote device
Title case.

2020-11-22 17:08 UTC, lalith1403 commented on articles/secured-deeplearning-in-remote-devices/index.md
> +#### Distributing the Training Dataset to each Worker
title case

2020-11-22 17:08 UTC, lalith1403 commented on articles/secured-deeplearning-in-remote-devices/index.md
> +#### Function for Model training
title case

2020-11-22 17:15 UTC, srishilesh commented on articles/secured-deeplearning-in-remote-devices/index.md
> +Generally, in any end-user device using Deep learning, the data is sent to the cloud, the predictions/classifications are made, and the results are returned to the end-users. Here, as end-users, we s
Sure. Thanks for the suggestion

2020-11-22 17:26 UTC, srishilesh commented
Hi @lalith1403 . Thanks for the review. I have made the requested changes. Please let me know, if I have missed out any.

2020-11-23 19:37 UTC, hectorkambow commented
@srishilesh 👋  Thank you for submitting your "Secured Deep Learning in Remote Devices" learn a bit about Deep learning in remote devices - please be sure to go over the changes I made to your article to be sure to implement any similar changes moving forward to other articles 🚀  
Fixed some sentences that were a bit difficult to understand (FYI) That may lead to a tiered payout
Thank you!

2020-11-23 19:38 UTC, merged