Tips and Tricks for Deep Learning
section-io/engineering-education pull request #712
Opened 2020-11-23 13:41 UTC by Bayler

Fixed #602

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-11-25 00:50 UTC, hectorkambow commented
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

2020-11-25 13:25 UTC, lalith1403 requested changes
Well written article. I have mentioned a few additions. A Grammarly check ensures minimal grammatical errors after making the changes. Great job!

2020-11-25 13:25 UTC, lalith1403 commented on articles/tips-and-tricks-for-deep-learning/index.md
> +A comprehensive understanding of Deep Learning (DL) is essential before reading this article, as most of the concepts and techniques you'll encounter are advanced.
Can you guide them to sources that provide the material that you are looking for?

2020-11-25 13:25 UTC, lalith1403 commented on articles/tips-and-tricks-for-deep-learning/index.md
> +#### Data augmentation
Data Augmentation: Maintain uniformity throughout the article. Make changes wherever necessary.

2020-11-25 13:25 UTC, lalith1403 commented on articles/tips-and-tricks-for-deep-learning/index.md
> +One of the drivers, aged 50, has covered a mileage of 100,000 while another driver, aged 25, has only covered 1,000 miles on their cars. The mileage and age data from these two drivers vary widely th
Rephrase the first sentence as, Consider a scenario where data related to two car drivers exists. One of them, aged 50, has covered 10000 while another, aged 25, has driven 1000 miles. 

Also, mileage might not be the right term here. Mileage refers to Km/Litre of fuel.

2020-11-25 13:25 UTC, lalith1403 commented on articles/tips-and-tricks-for-deep-learning/index.md
> +2. An imbalanced gradient that leads to the exploding gradient problem. Read more about it [here](https://deepai.org/machine-learning-glossary-and-terms/exploding-gradient-problem/).
Explain what an exploding gradient causes and why it is bad.

2020-11-25 13:25 UTC, lalith1403 commented on articles/tips-and-tricks-for-deep-learning/index.md
> +To avoid the problems mentioned above, we normalize their ages and mileage inputs to fit on the same scale. From our example, we can scale down our mileage and age data to a scale of between 0 to 1.
Check with the mileage terminology once.

2020-11-25 13:25 UTC, lalith1403 commented on articles/tips-and-tricks-for-deep-learning/index.md
> +From my previous [article](https://www.section.io/engineering-education/basics-of-convolution-neural-networks/), I discussed how training is achieved by updating the weights of the neural network ite
The process of updation of weights is known as internal covariate shift? It's not clear what internal covariate shift is.

2020-11-25 13:25 UTC, lalith1403 commented on articles/tips-and-tricks-for-deep-learning/index.md
> +No. If we initialize all the parameters to the same value, we will get the same updates during training. This will make the model only learn the same features. That's not something we'd want in our m
This will make the model only learn the same features -> This results in the model learning the same features.

2020-11-25 13:25 UTC, lalith1403 commented on articles/tips-and-tricks-for-deep-learning/index.md
> +Xavier initialization is also known as the Glorot Initialization. It is a weight initialization technique used to initialize the weights in a deep neural network. This technique helps avoid neuron ac
Define what saturated and dead regions are. It is necessary to explain how Xavier's initialization solves a problem, and why most of the time, we just use random initialization.

2020-11-25 13:25 UTC, lalith1403 commented on articles/tips-and-tricks-for-deep-learning/index.md
> +By allowing the learning rate to vary during training, the training time tends to reduce and improves the results. Several methods set a different learning rate for each trainable parameter and adapt
Include a GIF showing the comparison of convergence of the different algorithms. I remember seeing them on Google images.

2020-11-25 13:25 UTC, lalith1403 commented on articles/tips-and-tricks-for-deep-learning/index.md
> +Why early stopping?
##### Why early stopping?

2020-11-25 13:25 UTC, lalith1403 commented on articles/tips-and-tricks-for-deep-learning/index.md
> +Why early stopping?
add a H4 or H5 header.

2020-11-25 13:30 UTC, Bayler commented
Noted @lalith1403 Let me work on the corrections

2020-11-25 19:13 UTC, hectorkambow commented
plagiarism check done

2020-11-26 14:03 UTC, lalith1403 approved these changes

2020-11-27 04:03 UTC, merged