Introduction to Digital Twin Technology
section-io/engineering-education pull request #713
Opened 2020-11-23 15:35 UTC by mbaabuones

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

This PR fixes #694

2020-11-23 15:49 UTC, mbaabuones commented
@hectorkambow Im very sorry for having 10 commits in this PR. This is contrary to your initial request. I must admit I am facing a challenge especially when creating new branches. Every time I create a new PR, I always find files files from my other PR(s). I am forced to delete the unrequired files. Im kindly requesting for your guidance on how I can submit all my files in a single commit without affecting other PRs.

2020-11-25 00:16 UTC, hectorkambow commented
> @hectorkambow Im very sorry for having 10 commits in this PR. This is contrary to your initial request. I must admit I am facing a challenge especially when creating new branches. Every time I create a new PR, I always find files from my other PR(s). I am forced to delete the unrequired files. Im kindly requesting for your guidance on how I can submit all my files in a single commit without affecting other PRs.

👋  Not a problem - and thank you for asking for help. 

I don't recall if I've shared this video with you - but these short videos really helped me out a lot when I was brand new to GitHub and Git flows. 

- [GIT: Working with Branches](https://www.youtube.com/watch?v=JTE2Fn_sCZs&t=127s)
- [How to Upload Folder and Files in Github Repositories](https://www.youtube.com/watch?v=wXGa0bDvFWA&t=159s)
- [1.6: Cloning Repo and Push/Pull - Git and GitHub for Poets](https://www.youtube.com/watch?v=yXT1ElMEkW8&t=136s)
- [1.3: Forks and Pull Requests - Git and GitHub for Poets](https://www.youtube.com/watch?v=_NrSWLQsDL4)
- [Git & GitHub Tutorial for Beginners #11 - Collaborating on GitHub](https://www.youtube.com/watch?v=MnUd31TvBoU&t=513s)

These will explain how to work with branches (each new article - in your text editor should be on a new branch) that way when you create a PR it only uploads that one branch.

Hope this helps - please feel free to ping me if you have any other questions. 🚀

2020-11-25 16:03 UTC, lalith1403 requested changes
Amazing article. It needs a bit of restructuring. I have given a few suggestions. The fact that it is a digital twin of a live process is not clear in the article. You need to emphasize that and then proceed with the characteristics. Probably include an application in the beginning. That way, the reader's attention is retained. Also, a Grammarly check after the edits would ensure minimal errors. 

Also, check for lengthy sentences on hemingwayapp.com. Good job! Cheers.

2020-11-25 16:03 UTC, lalith1403 commented on articles/introduction-to-digital-twin-technology/index.md
> +### What is a Digital Twin?
I think you need to emphasize the twin simulated technology part. That way, the entire article makes sense.

2020-11-25 19:28 UTC, hectorkambow commented
plagiarism check done

2020-11-26 17:25 UTC, mbaabuones commented on articles/introduction-to-digital-twin-technology/index.md
> +Continuous learning and updates enable the digital twin to provide the real-time position, condition, or status of the real objects. This pairing of the real world and the digital representation enab
I have rephrased it.

2020-11-26 17:25 UTC, mbaabuones commented on articles/introduction-to-digital-twin-technology/index.md
> +### What is a Digital Twin?
I have revised the introduction section.

2020-11-26 17:25 UTC, mbaabuones commented on articles/introduction-to-digital-twin-technology/index.md
> +A Digital twin enables a company to detect problems in a product or manufacturing process. Through digital technology, outcomes can be predicted effectively with a high level of accuracy. With this t
Done.

2020-11-26 17:25 UTC, mbaabuones commented on articles/introduction-to-digital-twin-technology/index.md
> +Digital technology should be considered by organizations for various reasons. It enables companies to develop a digital footprint of the entire product life cycle. This ensures that they have an in-d
I have modified this part.

2020-11-26 17:26 UTC, mbaabuones commented on articles/introduction-to-digital-twin-technology/index.md
> +The digital twin model is achieved through six main features-sensors, actuators, data, integration, analytics, and the digital twin.
I have restructured the article. I have also revised the section on 'how digital twin technology works'.

2020-11-26 17:27 UTC, mbaabuones commented on articles/introduction-to-digital-twin-technology/index.md
> +- **Sensors:** Sensors are positioned at various points of the physical manufacturing process to collect data. Some of the important dimensions of data collected include works in progress (including
Done.

2020-11-26 17:29 UTC, mbaabuones commented
@lalith1403 Thank you for your comments and suggestions. I have finished working on the changes.

2020-11-27 16:45 UTC, lalith1403 commented
@hectorkambow There are merge conflicts. Can you suggest the next set of actions? The changes made are excellent. This is ready for the final round of review.

2020-11-27 16:48 UTC, hectorkambow commented
There is a merge conflict with this PR 
If you could please migrate the most updated .index file and all image to a new PR to be merged. (that should be a separate branch)
Thank you
![Uploading image.png…]()

2020-11-30 09:52 UTC, mbaabuones commented
> There is a merge conflict with this PR
> If you could please migrate the most updated .index file and all image to a new PR to be merged. (that should be a separate branch)
> Thank you
> ![image](https://user-images.githubusercontent.com/60800358/100470619-d105a300-3095-11eb-9823-ad077280d228.png)
> 
> The image was taken from our [FAQ](https://github.com/section-io/engineering-education/blob/master/new_contributors/FAQ.md)

@hectorkambow Done.

2020-11-30 15:11 UTC, closed without merging