Correcting Dataset Shift in Machine Learning
section-io/engineering-education pull request #740
Opened 2020-11-26 17:38 UTC by collins-a

Article on correcting dataset shift in ML as index.md.
Hero image as hero.jpg.
Other images include covariate.png, covariate2.png, and prior2.png

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-11-26 17:40 UTC, collins-a commented
This fixes #688

2020-11-27 16:24 UTC, hectorkambow commented
plagiarism check done

2020-11-29 14:54 UTC, lalith1403 requested changes
Minor improvements and this should be ready for the final round of review. After editing, check for errors on Grammarly to ensure minimal errors.

2020-11-29 14:54 UTC, lalith1403 commented on articles/correcting-data-shift/index.md
> +A general understanding of machine learning is required. This [post](Supervised Learning Algorithms | Section) can provide an introduction or refresher.
This link is invalid. Check this once.

2020-11-29 14:54 UTC, lalith1403 commented on articles/correcting-data-shift/index.md
> +For more on this type of shift, check out this [book]( Dataset Shift in Machine Learning (Neural Information Processing) (acad.bg)).
LINK IS INVALID

2020-11-29 14:54 UTC, lalith1403 commented on articles/correcting-data-shift/index.md
> +When you have training examples that are very similar to test examples, it is necessary to up-weight the training examples. This makes it seem like the training data was taken from the test set. Each
What do you mean by up weight the training examples? Can you explain more?

2020-11-29 17:09 UTC, collins-a commented
@lalith1403 as usual, thank you for your feedback. Cheers!

2020-11-30 16:09 UTC, lalith1403 approved these changes

2020-11-30 20:44 UTC, hectorkambow commented
@collins-a  🚀  
Thank you for the great article - just finishing up my final review. 
Please be sure to go over the edits to see where we can continue to improve the overall readability of the aritcles. 👍

2020-11-30 20:44 UTC, merged

2020-12-01 10:53 UTC, collins-a commented
@hectorkambow noted sir. Thank you