Basics of The Object Model
section-io/engineering-education pull request #764
Opened 2020-11-30 09:10 UTC by JudyNduati

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-11-30 09:12 UTC, JudyNduati commented
This fixes #665

2020-11-30 19:53 UTC, kayere requested changes
Great article @JudyNduati, very informative. I have made a few suggestions. Please make the changes and the article will be good to go.

2020-11-30 19:53 UTC, kayere commented on articles/basics-of-the-object-model/index.md
> +The world has many continents. Each continent consists of many countries, and each state is made of cities.
I don't really see how the example explains what polymorphism is. Consider using a different one.

2020-11-30 19:53 UTC, kayere commented on articles/basics-of-the-object-model/index.md
> +Different properties and functions form a class of the hierarchy. Through hierarchy, a class can be composed of inter-related sub-classes, which can have their sub-classes until the smallest level of
Could you please explain this concept further. It seems difficult to understand at a glance.

2020-11-30 19:53 UTC, kayere commented on articles/basics-of-the-object-model/index.md
> +Modularity refers to dividing a program into components or modules to reduce the problem's complexity. Modularity takes place on broad and powerful applications with multiple classes. The modules hel
Please elaborate on how modularity and encapsulation are related.

2020-11-30 19:53 UTC, kayere commented on articles/basics-of-the-object-model/index.md
> +That's all there is for this article. I hope this article gives you an understanding of the object model and its techniques.
Could you please make the conclusion a bit longer?

2020-12-01 00:24 UTC, hectorkambow commented
👋 Hi @JudyNduati 
Thank you for submitting your "Basics of The Object Model" article - it looks like it will be a helpful article. 

Upon running your article through our 3rd party plagiarism checker, it raised a few red flags (more than we typically see) 
Please see the attachment. 

& be sure to consult our [plagiarism resource](https://www.scribbr.com/category/plagiarism/
[Basics of Object Model.pdf](https://github.com/section-io/engineering-education/files/5619488/Basics.of.Object.Model.pdf)
) to get a clear understanding on how to avoid it.

2020-12-01 15:58 UTC, JudyNduati commented
Thank you @kayere and @hectorkambow, I made the changes you suggested and worked on the red flags. Kindly have a review.

2020-12-01 19:02 UTC, JudyNduati commented
Thank you @kayere and @hectorkambow, I made the changes you suggested and worked on the red flags. Kindly have a review

2020-12-01 20:22 UTC, kayere approved these changes
Great work making the changes @JudyNduati.

2020-12-02 01:40 UTC, merged