Autoscaling in Amazon Web Services (AWS): An Overview
section-io/engineering-education pull request #766
Opened 2020-11-30 10:02 UTC by mbaabuones

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #626 . This PR has been created because the previous PR has a merge conflict.

2020-12-01 23:57 UTC, hectorkambow commented
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

2020-12-06 02:28 UTC, cyberShaw commented
I'll do a review by EOD today. @mbaabuones

2020-12-09 20:44 UTC, hectorkambow commented
@cyberShaw 
Just trying to get a status update on this article 🚀

2020-12-10 09:27 UTC, cyberShaw requested changes
Great article, @mbaabuones!

There were very few things to change, so I combined the tech and the initial review into one. Please make the suggested changes and we can get this ready for final review.

2020-12-10 09:27 UTC, cyberShaw commented on articles/autoscaling-in-aws/index.md
> +
Really good article, @mbaabuones!
I have one suggestion, could you please add a section where you give a mini-tutorial on how to set up auto scaling on an instance. 
Your article provided very good insight on Autoscaling, but I felt the article would provide more value if you give some hands-on to the topic you're discussing about.

2020-12-12 12:48 UTC, mbaabuones commented
@cyberShaw Thank you for your suggestions. I have finished working on all the changes.

2020-12-14 17:12 UTC, cyberShaw commented
> @cyberShaw Thank you for your suggestions. I have finished working on all the changes.

Amazing work, I checked out the changes and they look really good.
This article is polished and is ready for final review. 🔥

2020-12-14 17:13 UTC, cyberShaw commented
@mbaabuones Can you add a hero image for this article?

2020-12-14 22:57 UTC, merged