how-css-works-behind-the-scenes
section-io/engineering-education pull request #770
Opened 2020-11-30 12:12 UTC by sardug10

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-12-01 14:42 UTC, lalith1403 requested changes
Some minor changes are required. I have made a few. Go through those minor errors. Also, technically this article explains the concepts well! Good job!

2020-12-01 14:42 UTC, lalith1403 commented on articles/how-css-works-behind-the-scenes/index.md
> +2. **Processing the real values**
Check the numbering.

2020-12-01 15:16 UTC, sardug10 commented
Hey, I am still not very comfortable with Github, so I just want to know the meaning of the label you have added i.e, **needs front matter**. Can you tell, what does it means and how can I resolve it? I will be very thankful to you! Also, I think I have resolved the issue of capitalizing the first letter of each sentence and the numbers issue in a single commit. So, if you can confirm that too? Thank you again!

2020-12-01 16:32 UTC, lalith1403 commented
The labels are for the information of the section managers. Information to be passed to the reader is done via GitHub comments, such as this one.

2020-12-01 17:47 UTC, sardug10 commented
> The labels are for the information of the section managers. Information to be passed to the author is done via GitHub comments, such as this one.

Okay......I am really sorry about that misunderstanding!

2020-12-01 18:35 UTC, hectorkambow commented
plagiarism check done 👍

2020-12-02 17:37 UTC, sardug10 commented
Hey, Do I need to make some changes to this or is it done from my side? Just making sure because this is my first time. Thank you!!

2020-12-02 17:39 UTC, hectorkambow commented
@sardug10 It looks like its ready for a final review (from me) - if anything else is needed I'll be sure to ping you 👍

2020-12-03 20:20 UTC, sardug10 commented on articles/how-css-works-behind-the-scenes/index.md
> +1. Do not use **!important** until it should not be given the highest priority.
Done!!

2020-12-04 14:50 UTC, lalith1403 commented
@hectorkambow the author has made the requested changes in the latest commit. Just pinging on his behalf. @sardug10 once you have made the necessary changes, ping us and let us know by dropping a comment. That way we can proceed further easily.

2020-12-04 15:13 UTC, sardug10 commented
> @hectorkambow the author has made the requested changes in the latest commit. Just pinging on his behalf. @sardug10 once you have made the necessary changes, ping us and let us know by dropping a comment. That way we can proceed further easily.

@lalith1403 I have made the requested changes that @hectorkambow told me to i.e, removing the double-negative in a sentence and I have also responded to him back quoting **"Done"** after solving that issue. If there are some more changes that I have to do, I will do it.

2020-12-06 18:39 UTC, sardug10 commented
Hello, A quick question:- When will be the article gets published and will I receive any payout from this as it was mentioned in the contribution guidelines.

2020-12-06 18:42 UTC, hectorkambow commented
> Hello, A quick question:- When will be the article gets published and will I receive any payout from this as it was mentioned in the contribution guidelines.

👋  @sardug10  Hello - yes payouts [are covered in our docs here](https://github.com/section-io/engineering-education/blob/master/new_contributors/CONTRIBUTING.md#review-approval--payment-processes) - the article will be published after a final review. (Which I believe this article may be ready for a final review - after that enhancement.)

2020-12-08 00:17 UTC, merged

2020-12-08 16:33 UTC, sardug10 commented
Hello, @hectorkambow...thank you for reviewing my article and publishing it. Just a last thing, I want to join the **sectionio-community on Slack** but I am unable to register to slack and it is telling me to get an invite from the **workspace administrator at sectionio-community**. Can you help me with this?