Data Lake vs. Data Warehouse vs. Database
section-io/engineering-education pull request #778
Opened 2020-11-30 13:59 UTC by EKahuha

this fixes #682

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-11-30 17:09 UTC, hectorkambow commented
Plagiarism check done

2020-12-01 11:14 UTC, lalith1403 requested changes
A few minor changes and this should be good to go. Congratulations on a well written article.

2020-12-01 11:14 UTC, lalith1403 commented on articles/data-lake-vs-data-warehouse-vs-database/index.md
> +### **An overview of data lake**
No need to bolden the headings.

2020-12-01 11:14 UTC, lalith1403 commented on articles/data-lake-vs-data-warehouse-vs-database/index.md
> +### **An overview of data lake**
Make changes throughout the article, wherever applicable.

2020-12-01 11:14 UTC, lalith1403 commented on articles/data-lake-vs-data-warehouse-vs-database/index.md
> +- **Healthcare**
Make this an H4 heading. Change accordingly throughout the article.

2020-12-01 11:14 UTC, lalith1403 commented on articles/data-lake-vs-data-warehouse-vs-database/index.md
> +The current shift towards cloud-based data platforms to mitigate data issues and manage data suggests that data lakes&#39; future is the cloud. The cloud is scalable and expandable, thus expected to
When you say the future of data lakes is in the cloud, isn't it already the case? I feel you should elaborate on how data lakes are being deployed via the cloud. That would make more sense.

2020-12-01 12:39 UTC, EKahuha commented
@lalith1403 
Done.

2020-12-01 14:08 UTC, lalith1403 approved these changes

2020-12-03 00:52 UTC, merged