Handling Imbalanced Datasets in Machine Learning
section-io/engineering-education pull request #784
Opened 2020-11-30 18:28 UTC by collins-a

Article as index.md.
Hero image as hero.jpg.
Other image; bagging.png.

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-11-30 18:28 UTC, collins-a commented
This fixes #645

2020-12-01 13:34 UTC, lalith1403 requested changes
A few minor changes and this should be good to go. Cheers!

2020-12-01 13:34 UTC, lalith1403 commented on articles/imbalanced-data-in-ml/index.md
> +For classification problems, there exists a method known as [Tomek links](http://www.samdrazin.com/classes/een548/project1report.pdf). It aims to improve the accuracy of the classification of data. T
Can you define class label noise? How is it different from support vector machines? Even SVMs try to maximize the distance between the decision boundary and the support vectors.

2020-12-01 13:34 UTC, lalith1403 commented on articles/imbalanced-data-in-ml/index.md
> +For classification problems, there exists a method known as [Tomek links](http://www.samdrazin.com/classes/een548/project1report.pdf). It aims to improve the accuracy of the classification of data. T
If similar, can support vectors act as tomek links? If different how?

2020-12-01 13:34 UTC, lalith1403 commented on articles/imbalanced-data-in-ml/index.md
> +Precision = True Positives / (True Positives + False Positives)
Consider wrapping it in $$ Precision = \frac{True Positives}{True Positives + False Positives} $$ It makes it more professional. Consider doing the same for all the formulas mentioned.

2020-12-01 13:34 UTC, lalith1403 commented on articles/imbalanced-data-in-ml/index.md
> +Precision = True Positives / (True Positives + False Positives)
Math JAX file is needed at the end. @hectorkambow Your help is needed with this once the edits are made.

2020-12-01 18:21 UTC, hectorkambow commented
plagiarism check done

2020-12-01 18:57 UTC, collins-a commented
@lalith1403 changes made. Thank you for direction regarding wrapping the formulas. Cheers, sir!

2020-12-02 12:59 UTC, lalith1403 approved these changes

2020-12-02 13:00 UTC, lalith1403 commented
@hectorkambow, the mathjax script might be needed. Can you also paste the same here to paste the script myself from next time whenever required?

2020-12-03 19:20 UTC, hectorkambow commented
> @hectorkambow, the mathjax script might be needed. Can you also paste the same here to paste the script myself from next time whenever required?

I've actually pinned it in our convo in Slack- thats where I copy it from 🚀

2020-12-03 19:20 UTC, merged