IoT Deployments with SD-WAN
section-io/engineering-education pull request #838
Opened 2020-12-05 16:32 UTC by EKahuha

this fixes #769

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-12-07 18:35 UTC, hectorkambow commented
Plagiarism check done

2020-12-09 14:09 UTC, lalith1403 requested changes
Excellent article. An additional section on keywords and its explanations should make this ready for final review.

2020-12-09 14:09 UTC, lalith1403 commented on articles/iot-deployments-with-sd-wan/index.md
> +This article will discuss how SD-WAN ensures successful IoT deployments and how it compares to the traditional wide area network (WAN).
Add a **Keywords** section. I observe you have mentioned many links. As a reader, I wouldn't be clicking on all the links. After some time, my attention would be fractured. Ensure the reader does not have to refer to many links.  
Explain:
- Overlay networks
- tunneling technology
- MPLS
- data packet
- E2EE
- VPN
- firewalls
and all the major concepts linked that add to the article.

2020-12-09 19:44 UTC, EKahuha commented
@lalith1403 
Updated.

2020-12-14 11:49 UTC, lalith1403 approved these changes

2020-12-14 19:26 UTC, merged