Introduction to room db
section-io/engineering-education pull request #874
Opened 2020-12-07 22:02 UTC by kayere

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #637

2020-12-12 16:43 UTC, LinusMuema requested changes
Hi @kayere 
This is an awesome article. Just a few notes and it will be good to go! 🙂 🙃

2020-12-12 16:43 UTC, LinusMuema commented on articles/introduction-to-room-db/index.md
> +Since we are going to record a sentence for each to-do item, we only need one field in the table. We annotate the field with `@PrimaryKey` to declare it the primary key for our table. There are many
You could add information about the autogenerating `id`'s in Room. I believe it is an important point for beginners in Room

2020-12-12 16:43 UTC, LinusMuema commented on articles/introduction-to-room-db/index.md
> +            return INSTANCE ?: synchronized(this) {
I think there is a lot more going on here that you have not explained. Could you provide info on what instance we are getting, why we are getting it, and how...I think that will cover the entire snippet. And about the parameters passed in the `@Database` annotation.

This is a technical issue

2020-12-14 13:46 UTC, LinusMuema commented
Awesome job @kayere 

@hectorkambow could you please give this article a final review...

2020-12-16 17:56 UTC, LinusMuema approved these changes

2020-12-17 20:38 UTC, hectorkambow commented
plagiarism check done

2020-12-17 20:38 UTC, merged