Digital Assistants vs. Digital Companions
section-io/engineering-education pull request #915
Opened 2020-12-10 11:04 UTC by Pius1991

This fixes #813

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-12-10 14:38 UTC, lalith1403 requested changes
Well written article. Congratulations on your first article. Make the changes. We will move it to the next round of review once everything looks good!

2020-12-10 14:38 UTC, lalith1403 commented on articles/digital-assistants-vs-digital-companions/index.md
> +1. Artificial Intelligence ([IA](https://www.section.io/engineering-education/artificial-intelligence-future/)) – Simulation of human intelligence through programming in a machine to mimic human acti
IA -> AI

2020-12-10 14:38 UTC, lalith1403 commented on articles/digital-assistants-vs-digital-companions/index.md
> +Digital companions have a two-way relationship with their users based on empathy, trust, and anticipation of needs and preferences. They make suggestions that fit our interests and positively influen
Have we moved so ahead in technology that digital companions have empathy and trust in them? The anticipation of needs is an actively studied ML problem. Can you clarify on the same? If these are characteristics of an ideal companion, mention that.

2020-12-10 14:38 UTC, lalith1403 commented on articles/digital-assistants-vs-digital-companions/index.md
> +- Digital assistants&#39; interactions are primarily command-based, but those of digital companions are both proactive and command-based.
Can you create a markdown table for this? Check this [link](https://www.makeuseof.com/tag/create-markdown-table/). A table would make it easier for the reader to compare the two.

2020-12-10 14:38 UTC, lalith1403 commented on articles/digital-assistants-vs-digital-companions/index.md
> +- Digital assistants incorporate very little information about the user while digital companions remember users` needs and preferences.
Don't use \` in markdown. Even if you want to use \` in your article, use \\` to represent the character. Moreover, ` is used for code formatting and variables highlighting in markdown. Let me know if you have any doubts regarding this.

2020-12-10 18:35 UTC, hectorkambow commented
plagiarism check done

2020-12-14 05:31 UTC, Pius1991 commented
@lalith1403 I have worked on the suggested revisions

2020-12-16 17:05 UTC, lalith1403 approved these changes

2020-12-16 18:43 UTC, lalith1403 commented
@Pius1991 can you check your avatar image? It says avatar.png.jpg... can you change the extension to avoid any errors?

2020-12-18 01:02 UTC, hectorkambow commented
@Pius1991 
Thank you for submitting your 1st article to the EngEd program - we are getting ready to publish your 1st article to the community. 
Please be sure to go over any edits (either I or our peer reviewer made) to get a better sense of the quality we expect moving forward - and see about implementing those into future articles. 🚀 

Be sure to check out our [resources page](https://github.com/section-io/engineering-education/blob/master/new_contributors/resources-page.md) - that has many useful resources to help us all become better technical writers as we continue to explore other great topics. 

cc @lalith1403 
👍 
Thank you

2020-12-18 01:04 UTC, merged