Addressing Underspecification in Machine Learning
section-io/engineering-education pull request #923
Opened 2020-12-11 08:51 UTC by collins-a

Article as index.md.
Hero image as hero.jpg

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-12-11 08:52 UTC, collins-a commented
this fixes #756

2020-12-14 00:19 UTC, hectorkambow commented
Plagiarism check done

2020-12-16 17:41 UTC, lalith1403 requested changes
I learned a lot from this article about underspecification. Amazing job, @collins-a. A few minor changes and this should be ready to go.

2020-12-16 17:41 UTC, lalith1403 commented on articles/underspecification/index.md
> +Consider a scenario where we are training many similar models on the same data. These models may differ in tiny ways, such as the number of training runs or the order in which training data is put in
model's real-world performance.

2020-12-16 17:41 UTC, lalith1403 commented on articles/underspecification/index.md
> +**Stratified Performance Evaluations**. An [inductive bias](http://inductivebias.com/Blog/what-is-inductive-bias/) refers to a set of assumptions that a learner uses to make predictions given never-b
The second sentence needs some more explanation. How do the inductive biases get tested for?

2020-12-16 17:41 UTC, lalith1403 commented on articles/underspecification/index.md
> +**Contrastive Evaluations**. These tests manipulate an input observation to compute the significance of the effect on the output. These evaluations support localized analysis of specific inductive bi
Does this come under explainable AI? If I can figure out which aspect contributes to the output, then can we explore this test for all models? What is the catch here?

2020-12-16 17:41 UTC, lalith1403 commented on articles/underspecification/index.md
> +##### Test Set that Reflects Deployment Environment
Test set reflecting deployment environment

2020-12-17 20:23 UTC, collins-a commented
@lalith1403 hey, I'm glad you found the article informative. I've made the needed minor changes. I hope they suffice. Catch you next article!

2020-12-21 20:33 UTC, merged