Introduction to theory of computation
section-io/engineering-education pull request #932
Opened 2020-12-12 06:09 UTC by OMONDIELLY

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)

- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

-created an Introduction to theory of computation article
-added image header for the article

2020-12-12 14:17 UTC, OMONDIELLY commented
This fixes #932

2020-12-15 00:18 UTC, hectorkambow commented
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

2020-12-18 17:16 UTC, OMONDIELLY commented
Looking forward to it being reviewed as soon as possible

On Tue, 15 Dec 2020, 3:18 AM hectorkambow <notifications@github.com> wrote:

> 👋 Thank you for submitting this PR - we will review it ASAP - all PRs go
> into our queue will be looked over before being approved to be published.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/section-io/engineering-education/pull/932#issuecomment-744869230>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJSCYTVHS3SZD4ESDLWEPF3SU2TO7ANCNFSM4UXYEDCQ>
> .
>

2020-12-22 07:55 UTC, OMONDIELLY commented
Hi Zolomohan, on the section just below reviewers, I am seeing a place asking still in progress, Convert to draft.. am I required to do anything?

2020-12-22 16:39 UTC, zolomohan commented
No. You can convert a PR to a draft if you want to make changes after you have submitted a PR. It will let us know that, the PR is still in progress.

You don't have to worry about it now.

2020-12-22 23:09 UTC, hectorkambow commented
plagiarism check done

2020-12-26 05:48 UTC, zolomohan requested changes
Overall, a good article. 
Although, I noticed a lot of grammatical errors. Please run this article through [Grammarly](https://www.grammarly.com/) to fix these errors.

Also, I've left some suggestions. Ping me when you have implemented them.

2020-12-26 05:48 UTC, zolomohan commented on articles/introduction-to-theory-of-computation/index.md
> +The essence of theory of computation is to help develop mathematical and logical models that run efficiently and to a point of halting.Since all machines that implement logic apply TOC, studying TOC
after theory of computation, mark the abbreviation in () like `(TOC)`.

2020-12-26 05:48 UTC, zolomohan commented on articles/introduction-to-theory-of-computation/index.md
> +[Automata Theory](https://en.wikipedia.org/wiki/Automata_theory) is basically the study of abstract computational devices and forms a formal framework for design and analysis new types of computing d
`design and analysis new types of computing devices`

after design and analysis, add `of`.

2020-12-26 05:48 UTC, zolomohan commented on articles/introduction-to-theory-of-computation/index.md
> +<!--more-->
remove `<!--more-->`. Here and all the places you have used it. This must be added only after the introduction and we will add it. You don't have to worry about it.

2020-12-26 05:48 UTC, zolomohan commented on articles/introduction-to-theory-of-computation/index.md
> +An Automaton is a logical unit of machine that operate singly on an input and follow a defined pattern or configuration so as to produce a desired output.
remove `so as`.

2020-12-26 05:48 UTC, zolomohan commented on articles/introduction-to-theory-of-computation/index.md
> +Finite Automata is useful in building text editors / text preprocessors.  FA are poor models of computer in that they can only perform simple computational tasks. Nonetheless, they are essential part
Add a period of `FA are poor models of computers`. and remove `in that`. `They can only ... `, frame it as a new sentence.

2020-12-26 05:48 UTC, zolomohan commented on articles/introduction-to-theory-of-computation/index.md
> +- **Context Free Grammars(CFGs)**  – are more powerful abstract models than FA and are essential in Programming Languages and Natural language research work
after essentially, add `used`.

2020-12-26 08:31 UTC, OMONDIELLY commented
Sure, will do that.

On Sat, 26 Dec 2020, 8:49 AM Mohan Raj <notifications@github.com> wrote:

> *@zolomohan* requested changes on this pull request.
>
> Overall, a good article.
> Although, I noticed a lot of grammatical errors. Please run this article
> through Grammarly <https://www.grammarly.com/> to fix these errors.
>
> Also, I've left some suggestions. Ping me when you have implemented them.
> ------------------------------
>
> In articles/introduction-to-theory-of-computation/index.md
> <https://github.com/section-io/engineering-education/pull/932#discussion_r548452636>
> :
>
> > +This article will cover:
>
> +
>
> +- [Introduction](#Overview)
>
> +- [Basics-of-Automata](#Automata-Basics)
>
> +- [Computability](#Computability)
>
> +- [Complexity](#Complexity)
>
> +- [Conclusion](#Conclusion)
>
> +
>
>
> Give this section a heading called Overview.
> This section should be below the introduction.
> ------------------------------
>
> In articles/introduction-to-theory-of-computation/index.md
> <https://github.com/section-io/engineering-education/pull/932#discussion_r548453183>
> :
>
> > +    alt: TOC cover image
>
> +
>
> +---
>
> +
>
> +
>
> +This article will cover:
>
> +
>
> +- [Introduction](#Overview)
>
> +- [Basics-of-Automata](#Automata-Basics)
>
> +- [Computability](#Computability)
>
> +- [Complexity](#Complexity)
>
> +- [Conclusion](#Conclusion)
>
> +
>
> +
>
> +### Introduction
>
> +**[Theory of computation]**(https://en.wikipedia.org/wiki/Theory_of_computation) is a branch of Computer Science that is concerned with how problems can be solved  using algorithms and how efficiently they can be solved
>
>
> Marking the text as bold must be done inside the []
> ------------------------------
>
> In articles/introduction-to-theory-of-computation/index.md
> <https://github.com/section-io/engineering-education/pull/932#discussion_r548944953>
> :
>
> > +---
>
> +
>
> +
>
> +This article will cover:
>
> +
>
> +- [Introduction](#Overview)
>
> +- [Basics-of-Automata](#Automata-Basics)
>
> +- [Computability](#Computability)
>
> +- [Complexity](#Complexity)
>
> +- [Conclusion](#Conclusion)
>
> +
>
> +
>
> +### Introduction
>
> +**[Theory of computation]**(https://en.wikipedia.org/wiki/Theory_of_computation) is a branch of Computer Science that is concerned with how problems can be solved  using algorithms and how efficiently they can be solved
>
> +Real world computers perform computations that by nature run like mathematical models to solve problems in systematic ways.
>
> +The essence of theory of computation is to help develop mathematical and logical models that run efficiently and to a point of halting.Since all machines that implement logic apply TOC, studying TOC gives learners an insight of computer hardware and software limitations
>
>
> after theory of computation, mark the abbreviation in () like (TOC).
> ------------------------------
>
> In articles/introduction-to-theory-of-computation/index.md
> <https://github.com/section-io/engineering-education/pull/932#discussion_r548945178>
> :
>
> > +
>
> +#### Importance of Theory of computation
>
> +The theory of computation forms the basis for:
>
> +* Writing efficient algorithms that run in computing devices
>
> +* Programming language research and their development.
>
> +* Efficient Compiler design and construction
>
> +<!--more-->
>
> +The Theory of Computation is made up of 3 branches i.e
>
> +- Automata Theory
>
> +- Computability Theory
>
> +- Complexity Theory
>
> +
>
> +
>
> +### Basic of Automata Theory
>
> +This branch of theoretical computer science was developed by mathematicians to simplify the logic of computation by using well defined abstract computational devices(models).
>
> +[Automata Theory](https://en.wikipedia.org/wiki/Automata_theory) is basically the study of abstract computational devices and forms a formal framework for design and analysis new types of computing devices such as bio computers and quantum computers.
>
>
> design and analysis new types of computing devices
>
> after design and analysis, add of.
> ------------------------------
>
> In articles/introduction-to-theory-of-computation/index.md
> <https://github.com/section-io/engineering-education/pull/932#discussion_r548945214>
> :
>
> > +The theory of computation forms the basis for:
>
> +* Writing efficient algorithms that run in computing devices
>
> +* Programming language research and their development.
>
> +* Efficient Compiler design and construction
>
> +<!--more-->
>
> +The Theory of Computation is made up of 3 branches i.e
>
> +- Automata Theory
>
> +- Computability Theory
>
> +- Complexity Theory
>
> +
>
> +
>
> +### Basic of Automata Theory
>
> +This branch of theoretical computer science was developed by mathematicians to simplify the logic of computation by using well defined abstract computational devices(models).
>
> +[Automata Theory](https://en.wikipedia.org/wiki/Automata_theory) is basically the study of abstract computational devices and forms a formal framework for design and analysis new types of computing devices such as bio computers and quantum computers.
>
> +These models are essential in several areas of computation (applied and theoretical fields).
>
> +<!--more-->
>
>
> remove <!--more-->. Here and all the places you have used it. This must
> be added only after the introduction and we will add it. You don't have to
> worry about it.
> ------------------------------
>
> In articles/introduction-to-theory-of-computation/index.md
> <https://github.com/section-io/engineering-education/pull/932#discussion_r548945878>
> :
>
> > +* Programming language research and their development.
>
> +* Efficient Compiler design and construction
>
> +<!--more-->
>
> +The Theory of Computation is made up of 3 branches i.e
>
> +- Automata Theory
>
> +- Computability Theory
>
> +- Complexity Theory
>
> +
>
> +
>
> +### Basic of Automata Theory
>
> +This branch of theoretical computer science was developed by mathematicians to simplify the logic of computation by using well defined abstract computational devices(models).
>
> +[Automata Theory](https://en.wikipedia.org/wiki/Automata_theory) is basically the study of abstract computational devices and forms a formal framework for design and analysis new types of computing devices such as bio computers and quantum computers.
>
> +These models are essential in several areas of computation (applied and theoretical fields).
>
> +<!--more-->
>
> +Through automata, we learn how  problems and compute functions are solved by use of automatons.
>
> +An Automaton is a logical unit of machine that operate singly on an input and follow a defined pattern or configuration so as to produce a desired output.
>
>
> remove so as.
> ------------------------------
>
> In articles/introduction-to-theory-of-computation/index.md
> <https://github.com/section-io/engineering-education/pull/932#discussion_r548946033>
> :
>
> > +
>
> +#### Branches of Automata Theory
>
> +
>
> +- **Finite Automata(FA)**- Is a kind of a computer though inferior in its computation ability. This model is fit for devices with limited memory. It is a simple abstract machine with 5 elements that define its functioning and processing of problems.
>
> +<!--more-->
>
> +Generally, a [Finite Automaton(FA)](https://www.geeksforgeeks.org/introduction-of-finite-automata/) is a finite collection of states with rules (transition functions) for traversing through the states depending on the input symbol.
>
> +FA accepts or rejects input strings while reading the strings from left to right.
>
> +**The tuples are –**
>
> ++ **Q:** *Finite set of states*
>
> ++ **∑:** *Set of input symbols*
>
> ++ **q:** *Initial state*
>
> ++ **F:** *Set of final states*
>
> ++ **δ:** *Transition function*
>
> +
>
> +<!--more-->
>
> +Finite Automata is useful in building text editors / text preprocessors.  FA are poor models of computer in that they can only perform simple computational tasks. Nonetheless, they are essential p [...]

2020-12-28 11:18 UTC, OMONDIELLY commented
@zolomohan , I have made the changes you requested

2020-12-28 12:17 UTC, zolomohan commented on articles/introduction-to-theory-of-computation/index.md
> +Involves analysis of the algorithm to determine how much time it takes while solving a problem. As T(n), running time is usually a complex expression when an algorithm runs on large input sizes. This
@OMONDIELLY 

What does T(n) mean here? And why is the running time usually a complex expression when the input size is large?
Isn't there a possibility of algorithms running on O(n) or O(1)?

I think this line is a bit unclear. Can you explain this a bit better?

2020-12-29 04:02 UTC, zolomohan requested changes

2020-12-29 04:02 UTC, zolomohan commented on articles/introduction-to-theory-of-computation/index.md
> +To evaluate the time and space complexity of an algorithm, a focus is made on the relative rate of growth of the time taken and the space taken to solve the problem as the size of the input grows. We
Can you add a link to an article that further explains Big Oh notation?

2020-12-29 08:40 UTC, OMONDIELLY commented
@Zolomohan, just to clarify something on the last 2  commits, I meant to push "link added " as the commit message  for 
9178845 instead of "updated link".
I wanted to ammend the  commit message but I decided not to.

2020-12-29 08:46 UTC, zolomohan commented
> @zolomohan, just to clarify something on the last 2 commits, I meant to push "link added " as the commit message for
> [9178845](https://github.com/section-io/engineering-education/commit/91788451813502de4bd9b7fea966629ce345844b) instead of "updated link".
> I wanted to ammend the commit message but I decided not to.

That's fine @OMONDIELLY.

2021-01-04 23:48 UTC, hectorkambow commented
@OMONDIELLY  👍  great job on your 1st article. 
Please be sure to go over any changes made by either myself of our peer reviewer to incorporate any applicable edits to future articles. 

Be sure to check out our [resources page](https://github.com/section-io/engineering-education/blob/master/new_contributors/resources-page.md) with helpful links meant to improve our communitys overall technical writing abilities.

2021-01-04 23:49 UTC, merged

2021-01-05 05:28 UTC, OMONDIELLY commented
Thanks..I'll be on the look for any changes and updates

On Tue, 5 Jan 2021, 2:49 AM hectorkambow <notifications@github.com> wrote:

> Merged #932 <https://github.com/section-io/engineering-education/pull/932>
> into master.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/section-io/engineering-education/pull/932#event-4167253842>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJSCYTXYBMRM476YQC3XP6LSYJHX5ANCNFSM4UXYEDCQ>
> .
>