Introduction to Android Views and Viewgroups
section-io/engineering-education pull request #934
Opened 2020-12-12 10:27 UTC by Dawe-7

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #720

2020-12-22 19:20 UTC, kayere requested changes
Hi @Dawe-7. I have gone through your article and suggested some corrections. Please make them. Also, add backticks to the names of the views and viewgroups.

2020-12-22 19:20 UTC, kayere commented on articles/introduction-to-android-views-and-view-groups/index.md
> +A ViewGroup is a view that can hold more views ( child class). The View group is the base class for containers, templates and views. Views use `LayoutParams` that serves to inform the parent class ho
"A ViewGroup is a view that holds other views" flows better.

2020-12-22 19:20 UTC, kayere commented on articles/introduction-to-android-views-and-view-groups/index.md
> +RelativeLayout displays views are relative to the others. The view position has some relation to the sibling.  You might be able to substitute many nested LinearLayout groups with a single RelativeLa
"RelativeLayout displays views relatively to one another" flows better. Rephrase the second sentence. It is too long.

2020-12-22 19:20 UTC, kayere commented on articles/introduction-to-android-views-and-view-groups/index.md
> +Example of RelativeLayout XML code snippet:
"Example of relative layout in XML" flows better.

2020-12-22 19:20 UTC, kayere commented on articles/introduction-to-android-views-and-view-groups/index.md
> +Example of LinearLayout XML code snippet:
Example of LinearLayout in XML

2020-12-22 19:20 UTC, kayere commented on articles/introduction-to-android-views-and-view-groups/index.md
> +- `android:id="@id/editText"` - The resource identified is EditTextView.
Replace EditTextView with EditText.

2020-12-22 19:20 UTC, kayere commented on articles/introduction-to-android-views-and-view-groups/index.md
> +- `android:layout_gravity="center"` - controls how frame layout aligns all the views it contains. The value you set affects both horizontal and vertical alignment of all child views within the single
controls how frame layout aligns the view it contains. not all the views. It is only one.

2020-12-22 19:20 UTC, kayere commented on articles/introduction-to-android-views-and-view-groups/index.md
> +In this article, we've gone through creating views and viewgroups. We have also seen some of the attributes associated with our views and viewgroups, where they are used and what they are used for. V
Views and viewgroups don't really give an application a unique feel since they are used in all applications.

2020-12-22 21:03 UTC, Dawe-7 commented
Hi @kayere 
I've made the requested changes, kindly review.
Thanks.

2020-12-23 08:36 UTC, kayere approved these changes
Hello @hectorkambow. Please give this article a final review.

2020-12-28 18:54 UTC, hectorkambow commented
👋 @Dawe-7 Thank you for submitting your Introduction to Android Views and Viewgroups article - this one has a similar issue in regards to the 3rd party plagiarism check.

It raised a few red flags and the % was a bit higher than typically accept.

This one is not as high in the % - but we just want to be sure we are providing appropriate sources (as links in the articles) where needed. 

The code snippets should also be as original and unique and possible (unless it is required frameworks or boilerplates).

Please review the PDF and be sure to add sources and citations to the article as articles where needed.

Here is a link to help with any [confusion regarding plagiarism](https://www.scribbr.com/category/plagiarism/) - as we strive to create both informative and unique content for the community.

Below is the PDF.
[Introduction to Android Views and Viewgroups #934.pdf](https://github.com/section-io/engineering-education/files/5748450/Introduction.to.Android.Views.and.Viewgroups.934.pdf)

Thank you 👍

2020-12-29 19:46 UTC, Dawe-7 commented
Hello @hectorkambow
I've added citations as links in the article as requested. The code snippets are required frameworks.
Kindly review.

2021-01-09 23:24 UTC, merged