Using picasso android
section-io/engineering-education pull request #949
Opened 2020-12-14 11:59 UTC by BrianaNzivu

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-12-14 12:00 UTC, BrianaNzivu commented
This fixes issue #623 .

2020-12-15 00:14 UTC, hectorkambow commented
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

2020-12-16 08:59 UTC, BrianaNzivu commented
@hectorkambow - No problem. 
Thank you for your patience.

2020-12-18 12:46 UTC, LinusMuema requested changes
Hi @BrianaNzivu 
This is an awesome article. Really informative.
Just a few suggestions and the article will be ready for final review. 

Side note: The last time I used Picasso in an android application, it had issues with caching images from URLs without image extensions, i.e, if an image URL does not end with `.png`, `.jpg` etc, Picasso won't cache it. I don't know if the issue was solved. If so, well and good. otherwise, inform the users

2020-12-18 12:46 UTC, LinusMuema commented on articles/using-picasso-in-android/index.md
> +- Full size caching.
You could give a short detail on what caching does in android especially for images. 

`caching allows for offline capabilities and less resource usage. It ensures the image is not downloaded every time it is needed.`

2020-12-18 12:46 UTC, LinusMuema commented on articles/using-picasso-in-android/index.md
> +- Priority requests
You could explain these uses more to give the user a richer understanding of the uses.

2020-12-18 12:46 UTC, LinusMuema commented on articles/using-picasso-in-android/index.md
> + case R.id.showTarget:
I think this case block goes to the `onClick` method. Make sure you separate these so as not to confuse the reader.
The same applies to other code blocks

2020-12-21 08:34 UTC, BrianaNzivu commented
Hey @LinusMuema . I have made the changes.
Kindly confirm if everything is OK now.
Regards.

2021-01-05 17:53 UTC, LinusMuema commented
Hi @BrianaNzivu 
I have made more changes. Please take a look for future references.

@hectorkambow you could give this article a final review.

2021-01-05 19:29 UTC, hectorkambow commented
plagiarism check done

2021-01-05 22:44 UTC, hectorkambow commented
👍  Great tutorial @BrianaNzivu  - it was super informative and well written 🚀  
cc: @LinusMuema

2021-01-05 22:45 UTC, merged