TensorFlow vs PyTorch: Which one to pick?
section-io/engineering-education pull request #965
Opened 2020-12-15 10:01 UTC by Bayler

Fixes #783

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-12-19 22:52 UTC, hectorkambow commented
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

2020-12-23 17:08 UTC, lalith1403 requested changes

2020-12-23 17:08 UTC, lalith1403 commented on articles/tensorflow-vs-pytorch/index.md
> +Deep Learning (DL) frameworks all center around deep learning and neural networks. If you haven't studied neural networks and how they function, please feel free to read this [article](https://www.se
These frameworks don't center around neural networks. They are gradient computing engines. Modify your statement.

2020-12-23 17:08 UTC, lalith1403 commented on articles/tensorflow-vs-pytorch/index.md
> +1. It is actively maintained by the developers at Google. Currently, TF2.3 is the latest released version.
Add link to tf2.3

2020-12-23 17:08 UTC, lalith1403 commented on articles/tensorflow-vs-pytorch/index.md
> +1. It is extremely fast and feels Native.
Remove unnecessary capitalization.

2020-12-23 17:08 UTC, lalith1403 commented on articles/tensorflow-vs-pytorch/index.md
> +6. Dynamic Computation Graphs is a key feature in PyTorch. It ensures that the graphs build up dynamically as you code.
Explain what a dynamic computation graph is. Add a section on static graphs vs. dynamic graphs and how it affects the performance. This section forms the heart of this article.

2020-12-23 17:08 UTC, lalith1403 commented on articles/tensorflow-vs-pytorch/index.md
> +Today, both frameworks allow both the static and dynamic computation of graphs. No much difference between the two as far as computation graphs are concerned.
Rewrite the last sentence. As far as computational graphs are concerned, not much difference exists between the two.

2020-12-23 17:08 UTC, lalith1403 commented on articles/tensorflow-vs-pytorch/index.md
> +As I mentioned earlier, TensorFlow has been around for a longer time compared to PyTorch. Due to this factor, and partly because Google's technology giants develop it, TensorFlow has a much wider com
This statement is actually wrong. The research community has embraced PyTorch really well. Therefore, I suggest you do some research and update this statement. PyTorch has a solid community presence.

2020-12-28 18:24 UTC, hectorkambow commented
plagiarism check done

2020-12-30 13:38 UTC, lalith1403 approved these changes

2021-01-04 18:47 UTC, merged