Introduction To Solid Principle
section-io/engineering-education pull request #966
Opened 2020-12-15 16:16 UTC by corpsgeek

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-12-15 16:17 UTC, corpsgeek commented
This pull request is linked to: https://github.com/section-io/engineering-education/issues/903

2020-12-19 22:40 UTC, hectorkambow commented
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

2020-12-20 12:35 UTC, corpsgeek commented
Alright.

2020-12-30 13:54 UTC, lalith1403 requested changes
Amazing article. I learned a lot about the SOLID principle and how to apply it. The examples are intuitive. Well done. A few minor changes and this should be good to go.

2020-12-30 13:54 UTC, lalith1403 commented on articles/introduction-to-solid-principle/index.md
> +In software development, the decision on how accessible and flexible an object is should occur during this object's design phase. This decision-making process pre-software development ensures usabili
Some clarity on the second sentence is required. Rewrite the sentence into 2 smaller sentences.

2020-12-30 13:54 UTC, lalith1403 commented on articles/introduction-to-solid-principle/index.md
> +Softwares change over time. Therefore developers need to build applications while keeping in mind the possibility of future changes. Poorly structured software applications make it difficult to refac
Software and code. We don't use softwares and codes.

2020-12-30 13:54 UTC, lalith1403 commented on articles/introduction-to-solid-principle/index.md
> +The SOLID principle is a design principle and pattern intended to make software designs more understandable, flexible, and maintainable. In the software development process, when creating an object ‒
What is a solid object or an abstract object?

2020-12-30 13:54 UTC, lalith1403 commented on articles/introduction-to-solid-principle/index.md
> +## LISKOV Substitution Principle
Use H3(###) and beyond. Change throughout the article wherever applicable.

2020-12-30 13:54 UTC, lalith1403 commented on articles/introduction-to-solid-principle/index.md
> +Above, we applied the MySQLDatabaseManagement class for performing database operations, and it carries out its function. The problem with the code above is if we decide to change our database type fr
Use formatting to refer to variable names. `MySQLDatabaseManagement`

2020-12-30 13:54 UTC, lalith1403 commented on articles/introduction-to-solid-principle/index.md
> +Above, we applied the MySQLDatabaseManagement class for performing database operations, and it carries out its function. The problem with the code above is if we decide to change our database type fr
Apply this accordingly throughout the article.

2020-12-30 13:54 UTC, lalith1403 commented on articles/introduction-to-solid-principle/index.md
> +In the above implementation, the CarManufacturer class does not rely on a concrete class. Rather it relies on an interface. Therefore, if we intend to change the database technology, we can change th
`CarManufacturer`

2020-12-30 22:03 UTC, corpsgeek commented
Alright, I will work on it. Thank you.

2020-12-31 13:21 UTC, corpsgeek commented
@lalith1403 revision complete.

2021-01-04 19:42 UTC, corpsgeek commented
@lalith1403 drawing your attention here post weekend🤗

2021-01-05 22:56 UTC, hectorkambow commented
Plagiarism check done 👍

2021-01-06 10:23 UTC, lalith1403 commented
The article is good to go. However, I found a few errors that I had resolved earlier. To avoid this, always pull the changes made before rectifying the errors.

2021-01-06 10:23 UTC, lalith1403 approved these changes

2021-01-06 10:44 UTC, corpsgeek commented
> The article is good to go. However, I found a few errors that I had resolved earlier. To avoid this, always pull the changes made before rectifying the errors.

Alright, thank you.

2021-01-10 00:44 UTC, hectorkambow commented
👋  Good evening @corpsgeek  

Just going over a final review for your article - it was very informative. 
Please be sure to go over the final edits I made to learn and carry over any applicable changes to future articles. 

There was a paragraph in there that was quite confusing, and I changed it altogether. 

I went ahead and made the changes to make the article flow - and I will be added a tiered payout label to this article (FYI). 

🚀 
cc @lalith1403

2021-01-10 00:45 UTC, merged

2021-01-10 19:26 UTC, corpsgeek commented
Thank you @hectorkambow. I’ve gone through the changes.