How AIOps is transforming IT operations
section-io/engineering-education pull request #975
Opened 2020-12-16 08:18 UTC by EKahuha

this fixes #865

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

2020-12-19 22:40 UTC, hectorkambow commented
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

2020-12-30 13:58 UTC, lalith1403 requested changes

2020-12-30 13:58 UTC, lalith1403 commented on articles/how-aiops-is-transforming-it-operations/index.md
> +AIOps reduces metrics such as the [Mean Time to Repair (MTTR) and the Mean Time to Detect (MTTD)](https://resolve.io/writable/documents/AIOps_For_Dummies-Nov19.pdf) dramatically. MTTR represents the
amount of time? Specify that.

2020-12-30 13:58 UTC, lalith1403 commented on articles/how-aiops-is-transforming-it-operations/index.md
> +Data silos is a common problem for many organizations and a source of inefficiency. Organizations faced with [data silos](https://www.plixer.com/blog/data-silo-what-is-it-why-is-it-bad/#) find that o
What is data silos? Can you elaborate on that?

2020-12-30 21:03 UTC, EKahuha commented
@lalith1403 
file updated

2021-01-04 15:07 UTC, lalith1403 approved these changes

2021-01-04 22:52 UTC, hectorkambow commented
👋  Good afternoon @EKahuha  

Giving your article a final review - its looking really good so far upon a quick glance. 

Wanted to ask if we could add a short sentence for the list you provide at the end - I think it would really add value to the reader and community to get a brief description of the AIops software you reference. 

Great job adding the links as well. Really helpful 🚀

2021-01-04 22:55 UTC, hectorkambow commented
plagiarism check done

2021-01-07 11:25 UTC, EKahuha commented
Good morning @hectorkambow 
I have updated this article. Please have a look.

2021-01-11 21:24 UTC, merged