Introduction to friend functions in C++
section-io/engineering-education pull request #985
Opened 2020-12-17 04:16 UTC by Dawe-7

### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #892

2020-12-22 21:48 UTC, hectorkambow commented
[Introduction to friend functions in C++.pdf](https://github.com/section-io/engineering-education/files/5732138/Introduction.to.friend.functions.in.C%2B%2B.pdf)
@Dawe-7  
Please go over this article again and be sure to provide sources and citations where needed. It seems like nearly half of your article is raising red flags in our 3rd party plagiarism checker.

2020-12-22 21:48 UTC, hectorkambow commented
@zolomohan Please wait for an improved .md file - and for us to do another plagiarism checker 👍

2020-12-23 18:07 UTC, Dawe-7 commented
Hello @hectorkambow,
I have improved the index.md file. Kindly review

2020-12-28 18:14 UTC, hectorkambow commented
👋 @Dawe-7  Thank you for submitting your Intro to friend functions in C++ article - it looks like its going to be very informative. 
[Introduction to friend functions in C++ #985.pdf](https://github.com/section-io/engineering-education/files/5748383/Introduction.to.friend.functions.in.C%2B%2B.985.pdf)


Quick FYI - upon running your article through our 3rd party plagiarism checker it raised a few red flags and the % was a bit higher than typically accept.

Please review the PDF and be sure to add sources and citations to the article as articles where needed.

Here is a link to help with any [confusion regarding plagiarism](https://www.scribbr.com/category/plagiarism/) - as we strive to create both informative and unique content for the community.

Below is the PDF.

Thank you 👍

2020-12-29 09:16 UTC, Dawe-7 commented
Hello @hectorkambow 
I've added the citations to the article. kindly review

2020-12-30 04:51 UTC, zolomohan commented
@hectorkambow. Let me know if this article is good to go. 
If it is, I'll start the review.

2021-01-06 11:25 UTC, zolomohan requested changes

2021-01-06 11:25 UTC, zolomohan commented on articles/introduction-to-friend-functions-in-c++/index.md
> +- `returnType` is the function return type.
```suggestion
- `returnType` is the function's return type.
```

2021-01-06 11:25 UTC, zolomohan commented on articles/introduction-to-friend-functions-in-c++/index.md
> +- `friend` is a keyword  to denote this a friend function.
```suggestion
- `friend` is a keyword to denote that this function a friend function.
```

2021-01-06 11:25 UTC, zolomohan commented on articles/introduction-to-friend-functions-in-c++/index.md
> +We have declared the friend function  `int mean` that takes objects as arguments. The function definition is outside the class's scope. The function uses the dot membership operator`.` and the object
```suggestion
We have declared the friend function `int mean` that takes objects as arguments. The function definition is outside the scope of the class. The function uses the dot membership operator `.` and the object passed as an argument to it to access the variables of the class `a` and `b`. The function call `mean(c)` passes by value the object `c`  to the friend function.
```

2021-01-06 11:25 UTC, zolomohan commented on articles/introduction-to-friend-functions-in-c++/index.md
> +Dawe, D. Introduction to friend functions in C++. Retrieved from https://www.programiz.com/cpp-programming/friend-function-class.
Can you add the resource title instead of `Dawe, D. Introduction to friend functions in C++.`

2021-01-06 11:28 UTC, zolomohan commented
@Dawe-7 When you add citations, you don't have to add the `<cite></cite>` tags.  Just a link is enough. Also please make sure that you use the proper resource name in the link.

2021-01-06 11:29 UTC, zolomohan commented on articles/introduction-to-friend-functions-in-c++/index.md
> +They are also used in operator overloading because they are more intuitive. The binary arithmetic operator which is commonly used can be overloaded the friend function way.
The operator overloading.

2021-01-06 14:03 UTC, Dawe-7 commented
@zolomohan I've made the requested changes. kindly review.

2021-01-09 13:19 UTC, zolomohan approved these changes

2021-01-09 13:20 UTC, zolomohan commented
@hectorkambow Please double check the citations on this article.

2021-01-10 02:12 UTC, merged